2 CONSTANT W/O
4 CONSTANT R/O
6 CONSTANT R/W

: BIN ;

: INCLUDE-FILE
    SAVE-INPUT N>R
    SOURCE-ID!
    0 BLK !
    BEGIN
        REFILL
    WHILE
        SOURCE ['] EVALUATE-RAW CATCH ?DUP IF
            NR> RESTORE-INPUT DROP
            THROW
        THEN
    REPEAT
    NR> RESTORE-INPUT DROP
;

: INCLUDED0
    R/O OPEN-FILE IF
        -38 THROW
    THEN
    INCLUDE-FILE
;

: INCLUDE0 BL WORD COUNT INCLUDED0 ;
