(   TITLE:  FATAN2 TESTS
     FILE:  FATAN2-TEST.FS
   AUTHOR:  DAVID N. WILLIAMS
  VERSION:  0.1.0
  LICENSE:  PUBLIC DOMAIN
  REVISED:  MARCH 27, 2009

VERSION 0.1.0
14MAR09 * STARTED.
19MAR09 * ADDED ANGLES TO COMPLETE THE CIRCLE.
23MAR09 * ADDED DEFINITIONS OF FRACTIONS OF PI IN TERMS OF PI,
	  WHICH AVOIDS MOST OF THE DECIMAL TO BINARY
	  CONVERSIONS.  SUGGESTED BY BERND PAYSAN.
27MAR09 * ADDED LINK TO KRISHNA MYNENI'S KFORTH VERSION.

THIS FILE TESTS THE ISO C / SINGLE UNIX 3 SPECIFICATION FOR
THE ANS FORTH FLOATING-EXT WORD:
)
\ FATAN2 ( F: Y X -- RADIANS ) OR ( Y X -- RADIANS )
(
IT EXPECTS THE RETURN VALUE TO BE THE PRINCIPAL ANGLE, AND
INCLUDES A NUMBER OF TESTS WITH +/-0, +/-NAN, AND +/-INF THAT
ARE NOT REQUIRED BY THE ANS FORTH 94 STANDARD.

A VERSION THAT WORKS WITH KFORTH CAN BE FOUND HERE:

  FTP://CCREWEB.ORG/SOFTWARE/KFORTH/EXAMPLES/FATAN2-TEST.4TH
)

CR .( RUNNING FATAN2-TEST.FS)
CR .( ----------------------) CR

\ FOR PFE:
S" FLOATING-EXT" ENVIRONMENT? [IF] DROP [THEN]

[UNDEFINED]  NAN [IF]  0E 0E F/ FCONSTANT  NAN [THEN]
[UNDEFINED] +INF [IF]  1E 0E F/ FCONSTANT +INF [THEN]
[UNDEFINED] -INF [IF] -1E 0E F/ FCONSTANT -INF [THEN]

\ S" ttester.FS" INCLUDED
TRUE VERBOSE !
DECIMAL

\ THE TTESTER DEFAULT FOR EXACT? IS TRUE.  UNCOMMENT THE
\ FOLLOWING LINE IF YOUR SYSTEM NEEDS IT TO BE FALSE:
\ SET-NEAR

VARIABLE #ERRORS    0 #ERRORS !

:NONAME  ( C-ADDR U -- )
(
DISPLAY AN ERROR MESSAGE FOLLOWED BY THE LINE THAT HAD THE
ERROR.
)
  1 #ERRORS +! ERROR1 ; ERROR-XT !

[UNDEFINED] \\ [IF]
  : \\  ( -- )  -1 PARSE 2DROP BEGIN REFILL 0= UNTIL ; [THEN]

[UNDEFINED] PI [IF]
 0.3141592653589793238463E1 FCONSTANT  PI
[THEN]
[UNDEFINED] -PI [IF]
 PI FNEGATE FCONSTANT -PI
[THEN]

FALSE [IF]
 0.7853981633974483096157E0 FCONSTANT   PI/4
-0.7853981633974483096157E0 FCONSTANT  -PI/4
 0.1570796326794896619231E1 FCONSTANT   PI/2
-0.1570796326794896619231E1 FCONSTANT  -PI/2
 0.4712388980384689857694E1 FCONSTANT  3PI/2
 0.2356194490192344928847E1 FCONSTANT  3PI/4
-0.2356194490192344928847E1 FCONSTANT -3PI/4
[ELSE]
 PI 4E F/   FCONSTANT   PI/4
-PI 4E F/   FCONSTANT  -PI/4
 PI 2E F/   FCONSTANT   PI/2
-PI 2E F/   FCONSTANT  -PI/2
 PI/2 3E F* FCONSTANT  3PI/2
 PI/4 3E F* FCONSTANT  3PI/4
-PI/4 3E F* FCONSTANT -3PI/4
[THEN]

VERBOSE @ [IF]
:NONAME  ( -- FP.SEPARATE? )
  DEPTH >R 1E DEPTH >R FDROP 2R> = ; EXECUTE
CR .( FLOATING-POINT AND DATA STACKS )
[IF] .( *SEPARATE*) [ELSE] .( *NOT SEPARATE*) [THEN]
CR
[THEN]

TESTING NORMAL VALUES

\ INPUT X-Y VALUES TAKEN FROM ED, COMP.LANG.FORTH,
\ "RE: AMBIGUITY IN FATAN2", 14MAR09, 17MAR09:
\   Y   X              RAD          DEG
T{  0E  1E FATAN2 ->   0E }T    \   0
T{  1E  1E FATAN2 ->   PI/4 }T    \  45
T{  1E  0E FATAN2 ->   PI/2 }T    \  90

T{ -1E -1E FATAN2 -> -3PI/4 }T    \ 135
T{  0E -1E FATAN2 ->   PI   }T    \ 180
T{ -1E  1E FATAN2 ->  -PI/4 }T    \ 225
T{ -1E  0E FATAN2 ->  -PI/2 }T    \ 270
T{ -1E  1E FATAN2 ->  -PI/4 }T    \ 315

TESTING SINGLE UNIX 3 SPECIAL VALUES SPEC

\ ISO C / SINGLE UNIX SPECIFICATION VERSION 3:
\   HTTP://WWW.UNIX.ORG/SINGLE_UNIX_SPECIFICATION/
\ SELECT "TOPIC", THEN "MATH INTERFACES", THEN "ATAN2()":
\   HTTP://WWW.OPENGROUP.ORG/ONLINEPUBS/009695399/FUNCTIONS/ATAN2F.HTML

\ IF Y IS +/-0 AND X IS < 0, +/-PI SHALL BE RETURNED.
T{  0E -1E FATAN2 ->  PI }T
T{ -0E -1E FATAN2 -> -PI }T

\ IF Y IS +/-0 AND X IS > 0, +/-0 SHALL BE RETURNED.
T{  0E  1E FATAN2 ->  0E }T
T{ -0E  1E FATAN2 -> -0E }T

\ IF Y IS < 0 AND X IS +/-0, -PI/2 SHALL BE RETURNED.
T{ -1E  0E FATAN2 -> -PI/2 }T
T{ -1E -0E FATAN2 -> -PI/2 }T

\ IF Y IS > 0 AND X IS +/-0, PI/2 SHALL BE RETURNED.
T{  1E  0E FATAN2 -> PI/2 }T
T{  1E -0E FATAN2 -> PI/2 }T

TESTING SINGLE UNIX 3 SPECIAL VALUES OPTIONAL SPEC

\ OPTIONAL ISO C / SINGLE UNIX SPECS:

\ IF EITHER X OR Y IS NAN, A NAN SHALL BE RETURNED.
T{ NAN  1E FATAN2 -> NAN }T
T{  1E NAN FATAN2 -> NAN }T
T{ NAN NAN FATAN2 -> NAN }T

\ IF Y IS +/-0 AND X IS -0, +/-PI SHALL BE RETURNED.
T{  0E -0E FATAN2 ->  PI }T
T{ -0E -0E FATAN2 -> -PI }T

\ IF Y IS +/-0 AND X IS +0, +/-0 SHALL BE RETURNED.
T{  0E  0E FATAN2 -> +0E }T
T{ -0E  0E FATAN2 -> -0E }T

\ FOR FINITE VALUES OF +/-Y > 0, IF X IS -INF, +/-PI SHALL BE RETURNED.
T{  1E -INF FATAN2 ->  PI }T
T{ -1E -INF FATAN2 -> -PI }T

\ FOR FINITE VALUES OF +/-Y > 0, IF X IS +INF, +/-0 SHALL BE RETURNED.
T{  1E +INF FATAN2 -> +0E }T
T{ -1E +INF FATAN2 -> -0E }T

\ FOR FINITE VALUES OF X, IF Y IS +/-INF, +/-PI/2 SHALL BE RETURNED.
T{ +INF  1E FATAN2 ->  PI/2 }T
T{ +INF -1E FATAN2 ->  PI/2 }T
T{ +INF  0E FATAN2 ->  PI/2 }T
T{ +INF -0E FATAN2 ->  PI/2 }T
T{ -INF  1E FATAN2 -> -PI/2 }T
T{ -INF -1E FATAN2 -> -PI/2 }T
T{ -INF  0E FATAN2 -> -PI/2 }T
T{ -INF -0E FATAN2 -> -PI/2 }T

\ IF Y IS +/-INF AND X IS -INF, +/-3PI/4 SHALL BE RETURNED.
T{ +INF -INF FATAN2 ->  3PI/4 }T
T{ -INF -INF FATAN2 -> -3PI/4 }T

\ IF Y IS +/-INF AND X IS +INF, +/-PI/4 SHALL BE RETURNED.
T{ +INF +INF FATAN2 ->  PI/4 }T
T{ -INF +INF FATAN2 -> -PI/4 }T

VERBOSE @ [IF]
CR .( #ERRORS: ) #ERRORS @ . CR
[THEN]

CR
CR .( END OF FATAN2-TEST.FS) CR
