\ PARANOIA
\
\ A FORTH VERSION OF WILLIAM KAHAN'S FLOATING POINT TEST PROGRAM, PARANOIA.
\ SEE DETAILED NOTES BELOW.
\
\ PORTED BY KRISHNA MYNENI
\
\ THIS VERSION IS BASED ON THE C PROGRAM, PARANOIA.C AT
\ 
\    HTTP://WWW.MATH.UTAH.EDU/~BEEBE/SOFTWARE/IEEE/
\
\ SEE COPYING GUIDELINES IN THE ORIGINAL COMMENTS BELOW. PLEASE NOTIFY
\
\    KRISHNA.MYNENI@CCREWEB.ORG
\
\ IF YOU FIND ANY ERRORS IN THIS FORTH TRANSLATION.
\
\ REVISIONS:
\    2009-05-19  KM;  V1.0 CREATED.
\    2009-05-20  DNW; CHANGED FE. TO FS.; ADDED SUPPORT FOR PFE
\                     (INITIALIZATION, CASE-SENSITIVITY PROBLEM),
\                     FIXED TYPO.
\                KM; SYSTEM-SPECIFIC INITIALIZATION FOR VFX FORTH
\                    AND BIGFORTH.
\   2009-05-25   KM; INCORPORATED CHANGES PRESENT IN THE NETLIB
\                    VERSION OF PARANOIA.C AT
\		     HTTP://WWW.NETLIB.ORG/PARANOIA/
\                    THE DESCRIPTION AT THE ORIGINAL SOURCE PAGE
\                    INDICATES THE NETLIB VERSION IS MORE UP TO DATE;
\                    ADDED CONDITIONAL DEFN. OF <=  AS SUGGESTED BY "ED"
\                    ON COMP.LANG.FORTH; ADDED PAUSE LOGIC FOR TESTING
\                    1/0 AND 0/0 IN PART8 -- PAUSING BEHAVIOR THROUGHOUT
\                    THE PROGRAM MAY BE SET WITH THE CONSTANT NOPAUSE
\   2010-04-21   KM; UPDATED KFORTH-SPECIFIC INITIALIZATION FOR
\                    CONDITIONAL DEFN. OF FLOATS
\ NOTES (BY KM):
\
\   1) THIS FORTH PROGRAM SHOULD RUN ON STANDARD FORTH-94 SYSTEMS WITH
\      FLOATING POINT EXTENSIONS. SEE SYSTEM-SPECIFIC INITIALIZATION
\      BELOW THESE COMMENTS.
\  
\   2) EITHER A SEPARATE FP STACK SYSTEM, OR AN INTEGRATED DATA/FP STACK
\      SYSTEM MAY BE USED. STACK DIAGRAMS FOR WORDS ARE SPECIFIED FOR A
\      SEPARATE FP SYSTEM.
\
\   3) SIGNAL HANDLING HAS BEEN COMMENTED OUT. THE COUNT OF FLOATING POINT
\      EXCEPTIONS, FPECOUNT, IS NOT VALID.
\
\   4) NO ATTEMPT HAS BEEN MADE TO FACTOR THE CODE ACCORDING TO GOOD FORTH
\      CODING PRACTICE. THIS FORTH PORT IS A "RAW" TRANSLATION, INTENDED TO
\      BE DIRECTLY COMPARABLE TO THE C CODE FROM WHICH IT WAS TRANSLATED.
\      SINCE THE PROGRAM EXAMINES ARITHMETIC PRECISION, CARE WAS TAKEN TO
\      AVOID MODIFYING THE ARITHMETIC EXPRESSIONS, I.E. CHANGING THE ORDER OF
\      OPERATIONS THAT COMMUTE MATHEMATICALLY, OR MODIFYING THEM FOR
\      FORTH-READABLE APPEARANCE. EVEN WHERE IT WOULD HAVE MADE SENSE TO USE
\      FLOATING POINT CONSTANTS RATHER THAN VARIABLES, THE TEMPTATION TO
\      DO SO WAS RESISTED IN THE FEAR THAT IT COULD CHANGE THE BEHAVIOR OF
\      THE PROGRAM.
\
\   5) OTHER, POSSIBLY MORE UP TO DATE, C AND FORTRAN VERSIONS OF PARANOIA
\      MAY BE FOUND AT THE FOLLOWING SITE:
\
\	HTTP://ORION.MATH.IASTATE.EDU/BURKARDT/C_SRC/PARANOIA/PARANOIA.HTML
\
\      THE OUTPUT FROM THE C VERSION AT THE ABOVE PAGE HAS BEEN COMPARED
\      TO THE OUTPUT FOR THIS FORTH VERSION, AND FOUND TO BE THE SAME FOR
\      TWO DIFFERENT FORTH SYSTEMS BY DAVID N. WILLIAMS.

\ ADD/UNCOMMENT YOUR SYSTEM-SPECIFIC INITIALIZATION BELOW; EXAMPLES FOR
\ KFORTH, PFE, VFX FORTH, AND BIGFORTH

\ FOR KFORTH

\ INCLUDE ANS-WORDS

CR .( RUNNING PARANOIA.4TH)
CR .( --------------------) CR
[UNDEFINED] FLOATS [IF] : FLOATS  DFLOATS ; [THEN]


\ FOR PFE
\ S" FLOATING-EXT" ENVIRONMENT? 0= [IF]
\  CR .( ** FLOATING-POINT EXTENSION WORDS NOT AVAILABLE **) CR ABORT
\ [THEN] ( FLAG) DROP

\ FOR VFX FORTH
(
INCLUDE HFP387.FTH
)

\ FOR BIGFORTH
(
IMPORT FLOAT  ALSO FLOAT
)


0 [IF]
	A C/C++ VERSION OF KAHAN'S FLOATING POINT TEST "PARANOIA"

			THOS SUMNER, UCSF, FEB. 1985
			DAVID GAY, BTL, JAN. 1986

	THIS IS A REWRITE FROM THE PASCAL VERSION BY

			B. A. WICHMANN, 18 JAN. 1985

	(AND DOES NOT EXHIBIT GOOD C PROGRAMMING STYLE).

(C) APR 19 1983 IN BASIC VERSION BY:
	PROFESSOR W. M. KAHAN,
	567 EVANS HALL
	ELECTRICAL ENGINEERING & COMPUTER SCIENCE DEPT.
	UNIVERSITY OF CALIFORNIA
	BERKELEY, CALIFORNIA 94720
	USA

CONVERTED TO PASCAL BY:
	B. A. WICHMANN
	NATIONAL PHYSICAL LABORATORY
	TEDDINGTON MIDDX
	TW11 OLW
	UK

CONVERTED TO C BY:

	DAVID M. GAY		AND	THOS SUMNER
	AT&T BELL LABS			COMPUTER CENTER, RM. U-76
	600 MOUNTAIN AVENUE		UNIVERSITY OF CALIFORNIA
	MURRAY HILL, NJ 07974		SAN FRANCISCO, CA 94143
	USA				USA

CONVERTED FOR K&R, STANDARD C, AND STANDARD C++ COMPILATION [WITH LOSS
OF SUPPORT FOR THE SPLIT SCRIPT BELOW] BY:

 	NELSON H. F. BEEBE
 	CENTER FOR SCIENTIFIC COMPUTING
 	UNIVERSITY OF UTAH
 	DEPARTMENT OF MATHEMATICS, 322 INSCC
 	155 S 1400 E RM 233
 	SALT LAKE CITY, UT 84112-0090
 	USA
 	EMAIL: BEEBE@MATH.UTAH.EDU, BEEBE@ACM.ORG, BEEBE@COMPUTER.ORG, BEEBE@IEEE.ORG (INTERNET)
 	WWW URL: HTTP://WWW.MATH.UTAH.EDU/~BEEBE
 	TELEPHONE: +1 801 581 5254
 	FAX: +1 801 585 1640, +1 801 581 4148

WITH SIMULTANEOUS CORRECTIONS TO THE PASCAL SOURCE (REFLECTED
IN THE PASCAL SOURCE AVAILABLE OVER NETLIB).
[A COUPLE OF BUG FIXES FROM DGH = SUN!DHOUGH INCORPORATED 31 JULY 1986.]

REPORTS OF RESULTS ON VARIOUS SYSTEMS FROM ALL THE VERSIONS
OF PARANOIA ARE BEING COLLECTED BY RICHARD KARPINSKI AT THE
SAME ADDRESS AS THOS SUMNER.  THIS INCLUDES SAMPLE OUTPUTS,
BUG REPORTS, AND CRITICISMS.

YOU MAY COPY THIS PROGRAM FREELY IF YOU ACKNOWLEDGE ITS SOURCE.
COMMENTS ON THE PASCAL VERSION TO NPL, PLEASE.


THE C VERSION CATCHES SIGNALS FROM FLOATING-POINT EXCEPTIONS.
IF SIGNAL(SIGFPE,...) IS UNAVAILABLE IN YOUR ENVIRONMENT, YOU MAY
#DEFINE NOSIGNAL TO COMMENT OUT THE INVOCATIONS OF SIGNAL.

THIS SOURCE FILE IS TOO BIG FOR SOME C COMPILERS, BUT MAY BE SPLIT
INTO PIECES.  COMMENTS CONTAINING "SPLIT" SUGGEST CONVENIENT PLACES
FOR THIS SPLITTING.  AT THE END OF THESE COMMENTS IS AN "ED SCRIPT"
(FOR THE UNIX(TM) EDITOR ED) THAT WILL DO THIS SPLITTING.

BY #DEFINING SINGLE WHEN YOU COMPILE THIS SOURCE, YOU MAY OBTAIN
A SINGLE-PRECISION C VERSION OF PARANOIA.


THE FOLLOWING IS FROM THE INTRODUCTORY COMMENTARY FROM WICHMANN'S WORK:

THE BASIC PROGRAM OF KAHAN IS WRITTEN IN MICROSOFT BASIC USING MANY
FACILITIES WHICH HAVE NO EXACT ANALOGY IN PASCAL.  THE PASCAL
VERSION BELOW CANNOT THEREFORE BE EXACTLY THE SAME.  RATHER THAN BE
A MINIMAL TRANSCRIPTION OF THE BASIC PROGRAM, THE PASCAL CODING
FOLLOWS THE CONVENTIONAL STYLE OF BLOCK-STRUCTURED LANGUAGES.  HENCE
THE PASCAL VERSION COULD BE USEFUL IN PRODUCING VERSIONS IN OTHER
STRUCTURED LANGUAGES.

RATHER THAN USE IDENTIFIERS OF MINIMAL LENGTH (WHICH THEREFORE HAVE
LITTLE MNEMONIC SIGNIFICANCE), THE PASCAL VERSION USES MEANINGFUL
IDENTIFIERS AS FOLLOWS [NOTE: A FEW CHANGES HAVE BEEN MADE FOR C;
I AND J AND PRECISION HAVE BEEN CHANGED FOR FORTH]:


BASIC   FORTH           BASIC   FORTH          BASIC   FORTH

   A                       J    JVAR               S    STICKYBIT
   A1   AINVERSE           J0   NOERRORS           T
   B    RADIX                    [FAILURE]         T0   UNDERFLOW
   B1   BINVERSE           J1   NOERRORS           T2   THIRTYTWO
   B2   RADIXD2                  [SERIOUSDEFECT]   T5   ONEANDHALF
   B9   BMINUSU2           J2   NOERRORS           T7   TWENTYSEVEN
   C                             [DEFECT]          T8   TWOFORTY
   C1   CINVERSE           J3   NOERRORS           U    ONEULP
   D                             [FLAW]            U0   UNDERFLOWTHRESHOLD
   D4   FOURD              K    PAGENO             U1
   E0                      L    MILESTONE          U2
   E1                      M                       V
   E2   EXP2               N                       V0
   E3                      N1                      V8
   E5   MINSQER            O    ZERO               V9
   E6   SQER               O1   ONE                W
   E7   MAXSQER            O2   TWO                X
   E8                      O3   THREE              X1
   E9                      O4   FOUR               X8
   F1   MINUSONE           O5   FIVE               X9   RANDOM1
   F2   HALF               O8   EIGHT              Y
   F3   THIRD              O9   NINE               Y1
   F6                      P    PRECISIONF         Y2
   F9                      Q                       Y9   RANDOM2
   G1   GMULT              Q8                      Z
   G2   GDIV               Q9                      Z0   PSEUDOZERO
   G3   GADDSUB            R                       Z1
   H                       R1   RMULT              Z2
   H1   HINVERSE           R2   RDIV               Z9
   I    IVAR               R3   RADDSUB
   IO   NOTRIALS           R4   RSQRT
   I3   IEEE               R9   RANDOM9

   SQRWRNG

ALL THE VARIABLES IN BASIC ARE TRUE VARIABLES AND IN CONSEQUENCE,
THE PROGRAM IS MORE DIFFICULT TO FOLLOW SINCE THE "CONSTANTS" MUST
BE DETERMINED (THE GLOSSARY IS VERY HELPFUL).  THE PASCAL VERSION
USES REAL CONSTANTS, BUT CHECKS ARE ADDED TO ENSURE THAT THE VALUES
ARE CORRECTLY CONVERTED BY THE COMPILER.

THE MAJOR TEXTUAL CHANGE TO THE PASCAL VERSION APART FROM THE
IDENTIFIERSIS THAT NAMED PROCEDURES ARE USED, INSERTING PARAMETERS
WHEREHELPFUL.  NEW PROCEDURES ARE ALSO INTRODUCED.  THE
CORRESPONDENCE IS AS FOLLOWS:


BASIC       PASCAL
LINES

  90- 140   PAUSE
 170- 250   INSTRUCTIONS
 380- 460   HEADING
 480- 670   CHARACTERISTICS
 690- 870   HISTORY
2940-2950   RANDOM
3710-3740   NEWD
4040-4080   DOESYEQUALX
4090-4110   PRINTIFNPOSITIVE
4640-4850   TESTPARTIALUNDERFLOW

[THEN]

\ 	BADCOND 		( N A U --  )
\ 	CHARACTERISTICS 	(  --  )
\ 	HEADING 		(  --  )
\ 	HISTORY 		(  --  )
\ 	INSTRUCTIONS 		(  --  )
\ 	ISYEQX 			(  --  )
\ 	NEWD 			(  --  )
\ 	PAUSE 			(  --  )
\ 	PRINTIFNPOSITIVE 	(  --  )
\ 	RANDOM 			( F: -- R )
\ 	SR3750 			(  --  )
\ 	SR3980 			(  --  )
\ 	SIGN 			( F: X -- ) ( -- N )
\ 	SQXMINX 		( N -- )
\ 	TSTCOND 		( N  VALID  A U -- )
\ 	TSTPTUF 		(  --  )
\ 	MAIN 			(  --  )
\ 	MSGLIST 		** NOT USED **
\ 	NOTIFY 			( A U -- )
\ 	POW 			( F: X Y -- U )


DECIMAL

S" [UNDEFINED]" PAD C! PAD CHAR+ PAD C@ MOVE
PAD FIND NIP 0=
[IF]
: [UNDEFINED]  ( "NAME" -- FLAG )
  BL WORD FIND NIP 0= ; IMMEDIATE
[THEN]

S" [DEFINED]" PAD C! PAD CHAR+ PAD C@ MOVE
PAD FIND NIP 0=
[IF]
: [DEFINED]  POSTPONE [UNDEFINED] 0= ; IMMEDIATE
[THEN]


[UNDEFINED] F~ 
[UNDEFINED] F<  OR
[UNDEFINED] F0= OR
[UNDEFINED] F** OR
[IF]
	.( **  REQUIRES  F**  AND  F~  AND  F<  AND  F0=  ** ) CR ABORT
[THEN] 

[UNDEFINED] FS. [IF]
[DEFINED] F. [IF]  
		: FS. F. ; 
	[ELSE] 
		.( **  REQUIRES  FS.  OR  F.  FOR OUTPUT  ** ) ABORT
	[THEN]
[THEN]


[UNDEFINED] F= [IF]
	: F= ( F: R1 R2 -- ) ( -- FLAG )
	    FDUP   F0= IF FABS THEN  FSWAP  
	    FDUP   F0= IF FABS THEN 
	    0E F~ ;
[THEN]

[UNDEFINED] F<> [IF] : F<> ( F: R1 R2 -- ) ( -- FLAG )   F= INVERT ;  [THEN]
[UNDEFINED] F>  [IF] 
	: F>  ( F: R1 R2 -- ) ( -- FLAG )
	    FOVER FOVER F< >R F= R> OR INVERT ;
[THEN]
[UNDEFINED] F<= [IF] : F<= ( F: R1 R2 -- ) ( -- FLAG )   F> INVERT ;  [THEN]
[UNDEFINED] F>= [IF] : F>= ( F: R1 R2 -- ) ( -- FLAG )   F< INVERT ;  [THEN]
[UNDEFINED] S>F [IF] : S>F ( N -- ) ( F: -- R )      	 S>D D>F ;    [THEN]

[UNDEFINED] <=     [IF] : <=  ( N1 N2 -- FLAG )  2DUP < >R = R> OR ;  [THEN]
[UNDEFINED] ?ALLOT [IF] : ?ALLOT ( U -- A ) HERE SWAP ALLOT ; [THEN]
[UNDEFINED] CELL-  [IF] : CELL- ( A1 -- A2 ) 1 CELLS - ;      [THEN]

\ --- ARRAYS (FSL-STYLE) ---

1 CELLS   CONSTANT  INTEGER

\ DEFINING WORD FOR 1-D ARRAY
: ARRAY ( N CELL_SIZE -- | -- ADDR )
    CREATE 2DUP SWAP 1+ * ?ALLOT ! DROP DOES> CELL+ ;

: }   ( ADDR N -- ADDR[N] | FETCH 1-D ARRAY ADDRESS)
    OVER CELL- @ * SWAP + ;

TRUE  CONSTANT NOPAUSE
TRUE  CONSTANT NOSIGNAL

VARIABLE SIGSAVE

FVARIABLE RADIX
FVARIABLE BINVRSE
FVARIABLE RADIXD2
FVARIABLE BMINUSU2


VARIABLE NOTRIALS  20 NOTRIALS !  \ NUMBER OF TESTS FOR COMMUTATIVITY.
	  
1  CONSTANT  YES
0  CONSTANT  NO
2  CONSTANT  CHOPPED
1  CONSTANT  ROUNDED
0  CONSTANT  OTHER
3  CONSTANT  FLAW
2  CONSTANT  DEFECT
1  CONSTANT  SERIOUS
0  CONSTANT  FAILURE


FVARIABLE  ZERO
FVARIABLE  HALF
FVARIABLE  ONE
FVARIABLE  TWO
FVARIABLE  THREE
FVARIABLE  FOUR
FVARIABLE  FIVE
FVARIABLE  EIGHT
FVARIABLE  NINE
FVARIABLE  TWENTYSEVEN
FVARIABLE  THIRTYTWO
FVARIABLE  TWOFORTY
FVARIABLE  MINUSONE
FVARIABLE  ONEANDHALF

VARIABLE INDX
CREATE CH 8 ALLOT
FVARIABLE AINVRSE
FVARIABLE A1
FVARIABLE C
FVARIABLE CINVRSE
FVARIABLE D
FVARIABLE FOURD
FVARIABLE E0
FVARIABLE E1
FVARIABLE EXP2
FVARIABLE E3
FVARIABLE MINSQER
FVARIABLE SQER
FVARIABLE MAXSQER
FVARIABLE E9
FVARIABLE THIRD
FVARIABLE F6
FVARIABLE F9
FVARIABLE H
FVARIABLE HINVRSE
VARIABLE IVAR  		\ INT I;
FVARIABLE STICKYBIT
FVARIABLE JVAR 		\ FLOAT J;
FVARIABLE MYZERO
FVARIABLE PRECISIONF
FVARIABLE Q
FVARIABLE Q9
FVARIABLE R
FVARIABLE RANDOM9
FVARIABLE T
FVARIABLE UNDERFLOW
FVARIABLE S
FVARIABLE ONEULP
FVARIABLE UFTHOLD
FVARIABLE U1
FVARIABLE U2
FVARIABLE V
FVARIABLE V0
FVARIABLE V9
FVARIABLE W
FVARIABLE X
FVARIABLE X1
FVARIABLE X2
FVARIABLE X8
FVARIABLE RANDOM1
FVARIABLE Y
FVARIABLE Y1
FVARIABLE Y2
FVARIABLE RANDOM2
FVARIABLE Z
FVARIABLE PSEUDOZERO
FVARIABLE Z1
FVARIABLE Z2
FVARIABLE Z9
4 INTEGER ARRAY ERRCNT{
VARIABLE FPECOUNT
VARIABLE MILESTONE
VARIABLE PAGENO
VARIABLE M
VARIABLE N
VARIABLE N1

VARIABLE GMULT
VARIABLE GDIV
VARIABLE GADDSUB

VARIABLE RMULT
VARIABLE RDIV
VARIABLE RADDSUB
VARIABLE RSQRT

VARIABLE BREAK
VARIABLE DONE
VARIABLE NOTMONOT
VARIABLE MONOT
VARIABLE ANOMALY
VARIABLE IEEE
VARIABLE SQRWRNG
VARIABLE UFNGRAD

\ COMPUTED CONSTANTS.
\ U1  GAP BELOW 1.0, I.E, 1.0-U1 IS NEXT NUMBER BELOW 1.0
\ U2  GAP ABOVE 1.0, I.E, 1.0+U2 IS NEXT NUMBER ABOVE 1.0

\ FLOATING POINT EXCEPTION RECEIVER
: SIGFPE ( I --  )
	1 FPECOUNT +!
	CR ." * * * FLOATING-POINT ERROR * * *" CR
	ABORT 
;

: BADCOND ( N A U -- )
	ROT DUP
	ERRCNT{ SWAP } 1 SWAP +!
	CASE
	  FAILURE OF ." FAILURE " ENDOF
	  SERIOUS OF ." SERIOUS " ENDOF
	  DEFECT  OF ." DEFECT "  ENDOF
	  FLAW    OF ." FLAW "    ENDOF
	ENDCASE
	TYPE
;


: TSTCOND ( N  VALID  A U -- )
	ROT 0=  IF  BADCOND ." ." CR  ELSE 2DROP DROP THEN
;

: INSTRUCTIONS ( -- )
	CR
	." LEST THIS PROGRAM STOP PREMATURELY, I.E. BEFORE DISPLAYING" CR CR
	."    `END OF TEST'," CR CR
	." TRY TO PERSUADE THE COMPUTER NOT TO TERMINATE EXECUTION WHEN AN" CR
	." ERROR LIKE OVER/UNDERFLOW OR DIVISION BY ZERO OCCURS, BUT RATHER" CR
	." TO PERSEVERE WITH A SURROGATE VALUE AFTER, PERHAPS, DISPLAYING SOME" CR
	." WARNING.  IF PERSUASION AVAILS NAUGHT, DON'T DESPAIR BUT RUN THIS" CR
	." PROGRAM ANYWAY TO SEE HOW MANY MILESTONES IT PASSES, AND THEN" CR
	." AMEND IT TO MAKE FURTHER PROGRESS." CR CR
	." ANSWER QUESTIONS WITH Y, Y, N OR N (UNLESS OTHERWISE INDICATED)." CR
;


: HEADING ( -- )
	." USERS ARE INVITED TO HELP DEBUG AND AUGMENT THIS PROGRAM SO IT WILL" CR
	." COPE WITH UNANTICIPATED AND NEWLY UNCOVERED ARITHMETIC PATHOLOGIES." CR
	." PLEASE SEND SUGGESTIONS AND INTERESTING RESULTS TO" CR CR
	." RICHARD KARPINSKI" CR
	." COMPUTER CENTER U-76" CR
	." UNIVERSITY OF CALIFORNIA" CR
	." SAN FRANCISCO, CA 94143-0704, USA" CR CR
	." IN DOING SO, PLEASE INCLUDE THE FOLLOWING INFORMATION:" CR CR
	." PRECISION: "
	1 FLOATS 
	CASE
		4 OF ." SINGLE" ENDOF
		8 OF ." DOUBLE" ENDOF
	       10 OF ." LONG DOUBLE" ENDOF
		1 FLOATS . ." BYTES"
	ENDCASE
	CR
	." VERSION: 10 FEBRUARY 1989; FORTH" CR
	." COMPUTER:" CR
	." COMPILER:" CR
	." OPTIMIZATION LEVEL:" CR
	." OTHER RELEVANT COMPILER OPTIONS:" CR
;


: CHARACTERISTICS ( -- )
	." RUNNING THIS PROGRAM SHOULD REVEAL THESE CHARACTERISTICS:" CR CR
	."     RADIX = 1, 2, 4, 8, 10, 16, 100, 256 ..." CR
	."     PRECISION = NUMBER OF SIGNIFICANT DIGITS CARRIED." CR
	."     U2 = RADIX/RADIX^PRECISION = ONE ULP" CR
	." (ONEULPNIT IN THE LAST PLACE) OF 1.000XXX ." CR
	."     U1 = 1/RADIX^PRECISION = ONE ULP OF NUMBERS A LITTLE LESS THAN 1.0 ." CR
	."     ADEQUACY OF GUARD DIGITS FOR MULT., DIV. AND SUBT." CR
	."     WHETHER ARITHMETIC IS CHOPPED, CORRECTLY ROUNDED, OR SOMETHING ELSE" CR
	." FOR MULT., DIV., ADD/SUBT. AND SQRT." CR
	."     WHETHER A STICKY BIT USED CORRECTLY FOR ROUNDING." CR
	."     UNDERFLOWTHRESHOLD = AN UNDERFLOW THRESHOLD." CR
	."     E0 AND PSEUDOZERO TELL WHETHER UNDERFLOW IS ABRUPT, GRADUAL, OR FUZZY." CR
	."     V = AN OVERFLOW THRESHOLD, ROUGHLY." CR
	."     V0  TELLS, ROUGHLY, WHETHER  INFINITY  IS REPRESENTED." CR
	."     COMPARISIONS ARE CHECKED FOR CONSISTENCY WITH SUBTRACTION" CR
	." AND FOR CONTAMINATION WITH PSEUDO-ZEROS." CR
	."     SQRT IS TESTED.  Y^X IS NOT TESTED." CR
	."     EXTRA-PRECISE SUBEXPRESSIONS ARE REVEALED BUT NOT YET TESTED." CR
	."     DECIMAL-BINARY CONVERSION IS NOT YET TESTED FOR ACCURACY." CR
;

: HISTORY ( -- )
  \ HISTORY
  \ CONVERTED FROM BRIAN WICHMANN'S PASCAL VERSION TO C BY THOS SUMNER,
  \	WITH FURTHER MASSAGING BY DAVID M. GAY.

	." THE PROGRAM ATTEMPTS TO DISCRIMINATE AMONG" CR CR
	."   FLAWS, LIKE LACK OF A STICKY BIT," CR
	."   SERIOUS DEFECTS, LIKE LACK OF A GUARD DIGIT, AND" CR
	."   FAILURES, LIKE 2+2 == 5 ." CR CR
	." FAILURES MAY CONFOUND SUBSEQUENT DIAGNOSES." CR CR
	." THE DIAGNOSTIC CAPABILITIES OF THIS PROGRAM GO BEYOND AN EARLIER" CR
	." PROGRAM CALLED `MACHAR', WHICH CAN BE FOUND AT THE END OF THE" CR
	." BOOK  `SOFTWARE MANUAL FOR THE ELEMENTARY FUNCTIONS' (1980) BY" CR
	." W. J. CODY AND W. WAITE. ALTHOUGH BOTH PROGRAMS TRY TO DISCOVER" CR
	." THE RADIX, PRECISION AND RANGE (OVER/UNDERFLOW THRESHOLDS)" CR
	." OF THE ARITHMETIC, THIS PROGRAM TRIES TO COPE WITH A WIDER VARIETY" CR
	." OF PATHOLOGIES, AND TO SAY HOW WELL THE ARITHMETIC IS IMPLEMENTED." CR
	." THE PROGRAM IS BASED UPON A CONVENTIONAL RADIX REPRESENTATION FOR" CR
	." FLOATING-POINT NUMBERS, BUT ALSO ALLOWS LOGARITHMIC ENCODING" CR
	." AS USED BY CERTAIN EARLY WANG MACHINES." CR CR
	." BASIC VERSION OF THIS PROGRAM (C) 1983 BY PROF. W. M. KAHAN;" CR
	." SEE SOURCE COMMENTS FOR MORE HISTORY." CR
;

: NOTIFY ( A U -- )
	TYPE ."  TEST APPEARS TO BE INCONSISTENT..." CR
	."   PLEASE NOTIFY KARPINKSI!" CR
;



: PAUSE ( -- )
	NOPAUSE 0= IF
		CR ." TO CONTINUE, PRESS RETURN"
		KEY DROP CR
	THEN
	." DIAGNOSIS RESUMES AFTER MILESTONE NUMBER " MILESTONE ? CR
	."          PAGE: " PAGENO ? CR CR
	1 MILESTONE +!
	1 PAGENO +!
;



: SIGN  ( F: X -- Y )
	0E F>= IF 1.0E ELSE -1.0E THEN
;



\ RANDOM
\  RANDOM COMPUTES
\     X = (RANDOM1 + RANDOM9)^5
\     RANDOM1 = X - FLOOR(X) + 0.000005 * X;
\   AND RETURNS THE NEW VALUE OF RANDOM1
\


: RANDOM ( F: -- R )
	RANDOM1 F@ RANDOM9 F@ F+  \ F: -- R
	FDUP FDUP F*  FDUP F* F*  \ F: -- X
	FDUP FDUP FLOOR F-        \ F: -- X  X-FLOOR(X)
	FSWAP 0.000005E F* F+
;



FVARIABLE XA
FVARIABLE XB

: SQXMINX ( NERRKIND -- )

	X F@ BINVRSE F@ F*  XB F!
	X F@ XB F@ F- XA F!
	X F@ X F@ F* FSQRT XB F@ F-  XA F@ F- ONEULP F@ F/ SQER F!
	SQER F@ ZERO F@ F<>  IF
		SQER F@ MINSQER F@ F<  IF  SQER F@ MINSQER F!  THEN
		SQER F@ MAXSQER F@ F>  IF  SQER F@ MAXSQER F!  THEN
		JVAR F@ 1.0E F+ JVAR F!
		S" " BADCOND
		." SQRT( " X F@ X F@ F* FS. ( %.17E) ."  - " X F@ FS. ( %.17E) ."  = "
		ONEULP F@ * SQER F@ F* FS. ( %.17E) CR
		." INSTEAD OF CORRECT VALUE 0." CR
	ELSE DROP
	THEN
;


: NEWD ( -- )
	Z1 F@ Q F@ F* X F!
	HALF F@  X F@ RADIX F@ F/ F- FLOOR  RADIX F@ F*  X F@ F+  X F!
	Q F@ X F@ Z F@ F* F- RADIX F@ F/  X F@ X F@ F*  D F@ RADIX F@ F/ F* F+ Q F!
	Z F@  TWO F@ X F@ F* D F@ F*  F-  Z F!
	Z F@ ZERO F@ F<=  IF
		Z F@ FNEGATE Z F!
		Z1 F@ FNEGATE Z1 F!
	THEN
	RADIX F@ D F@ F* D F!
;



: SR3750 ( -- )
	X F@ RADIX F@ F-  Z2 F@ RADIX F@ F- F<
	X F@ Z2 F@ F-  W F@ Z2 F@ F- F>  OR INVERT IF
		1 IVAR +!
		X F@ D F@ F* FSQRT  X2 F!
		X2 F@ Z2 F@ F-  Y F@ Z2 F@ F-  F-  Y2 F!
		X8 F@  Y F@ HALF F@ F-  F/  X2 F!
		X2 F@  HALF F@ X2 F@ F* X2 F@ F*  F-  X2 F!
		Y2 F@ HALF F@ F+  HALF F@ X2 F@ F-  F+  SQER F!
		SQER F@ MINSQER F@ F< IF  SQER F@  MINSQER F! THEN
		Y2 F@ X2 F@ F-  SQER F!
		SQER F@ MAXSQER F@ F> IF  SQER F@  MAXSQER F! THEN
	THEN
;



: ISYEQX ( -- )
	Y F@ X F@ F<> IF
		N @ 0 <=  IF
			Z F@ ZERO F@ F=  Q F@ ZERO F@ F<=  AND IF
				." WARNING:  COMPUTING" CR
			ELSE 
				DEFECT S" COMPUTING" BADCOND
			THEN
			."   " Z F@ FS. ( %.17E) ." ^" Q F@ FS. ( %.17E) CR
			."     YIELDED " Y F@ FS. ( %.17E) CR
			."     WHICH COMPARED UNEQUAL TO CORRECT " X F@ FS. ( %.17E) CR
			."          THEY DIFFER BY " Y F@ X F@ F- FS. ( %.17E) CR
		THEN
		1 N +!  \ ... COUNT DISCREPANCIES.
	THEN
;


: POW ( F: X Y -- Z ) \ RETURN X ^ Y (EXPONENTIATION)
	F** ;


: SR3980 ( -- )
	BEGIN
		IVAR @ S>F Q F!
		Z F@ Q F@ POW  Y F!
		ISYEQX
		1 IVAR +!  IVAR @ M @ > IF  EXIT THEN
		Z F@ X F@ F* X F!
	X F@ W F@ F<  WHILE
	REPEAT 
;

 

: PRINTIFNPOSITIVE ( -- )
	N @ 0> IF
		." SIMILAR DISCREPANCIES HAVE OCCURRED " N ? ."  TIMES." CR
	THEN
;


 

: TSTPTUF ( -- )
	0 N !
	Z F@  ZERO F@ F<>  IF
		." SINCE COMPARISON DENIES Z = 0, EVALUATING "
		." (Z + Z) / Z SHOULD BE SAFE." CR
		\ SIGSAVE = SIGFPE;
		\ IF (SETJMP(OVFL_BUF)) GOTO VERY_SERIOUS;
		Z F@ Z F@ F+ Z F@ F/  Q9 F!
		." WHAT THE MACHINE GETS FOR (Z + Z) / Z IS  " ( %.17E)
			Q9 F@ F. CR
		Q9 F@ TWO F@ F- FABS  RADIX F@ U2 F@ F*  F< IF
			." THIS IS O.K., PROVIDED OVER/UNDERFLOW"
			."  HAS NOT JUST BEEN SIGNALED." CR
		ELSE
			Q9 F@ ONE F@ F<  Q9 F@ TWO F@ F> OR IF
\ VERY_SERIOUS:
				1 N !
				1 ERRCNT{ SERIOUS } +!
				." THIS IS A VERY SERIOUS DEFECT!" CR
			ELSE
				1 N !
				1 ERRCNT{ DEFECT } +!
				." THIS IS A DEFECT!" CR
			THEN
		THEN
		0 SIGSAVE !
		Z F@ ONE F@ F* V9 F!
		V9 F@ RANDOM1 F!
		ONE F@ Z F@ F* V9 F!
		V9 F@ RANDOM2 F!
		Z F@ ONE F@ F/ V9 F!

		Z F@ RANDOM1 F@ F=
		Z F@ RANDOM2 F@ F= AND
		Z F@ V9 F@ F= AND IF
			N @ 0> IF PAUSE THEN
			
		ELSE
			1 N !
			DEFECT S" WHAT PRINTS AS Z = " BADCOND
			( %.17E ) Z F@ FS. ." COMPARES DIFFERENT FROM  "
			Z F@ RANDOM1 F@ F<> IF ." Z * 1 = " ( %.17E) RANDOM1 F@ FS. THEN
			Z F@ RANDOM2 F@ F=
			RANDOM2 F@ RANDOM1 F@ F= OR INVERT  IF
				." 1 * Z == " RANDOM2 F@ F. CR
			THEN
			Z F@ V9 F@ F= INVERT IF ." Z / 1 = " ( %.17E) V9 F@ FS. CR THEN
			RANDOM2 F@ RANDOM1 F@ F<> IF
				1 ERRCNT{ DEFECT } +!
				DEFECT  S" MULTIPLICATION DOES NOT COMMUTE!" BADCOND
				." COMPARISON ALLEGES THAT 1 * Z = " ( %.17E)
					RANDOM2 F@ FS. CR
				." DIFFERS FROM Z * 1 = " ( %.17E) RANDOM1 F@ FS. CR
			THEN
			PAUSE
		THEN
	THEN
;


: PART2 ( -- )
	\ =============================================
	10 MILESTONE !
	\ =============================================
	FAILURE
	THREE F@ THREE F@ F* NINE F@ F=
	NINE F@ THREE F@ F* TWENTYSEVEN F@ F= AND
	FOUR F@ FOUR F@ F+ EIGHT F@ F= AND
	EIGHT F@ FOUR F@ F* THIRTYTWO F@ F= AND
	THIRTYTWO F@ TWENTYSEVEN F@ F- FOUR F@ F- ONE F@ F- ZERO F@ F= AND
	S" 9 != 3*3, 27 != 9*3, 32 != 8*4, OR 32-27-4-1 != 0"
	TSTCOND

	FAILURE
	FOUR F@ ONE F@ F+ FIVE F@ F=
	FOUR F@ FIVE F@ F* THREE F@ F* FOUR F@ F* TWOFORTY F@ F= AND
	TWOFORTY F@ THREE F@ F/ FOUR F@ FOUR F@ F* FIVE F@ F* F- ZERO F@ F= AND
	TWOFORTY F@ FOUR F@ F/  FIVE F@ THREE F@ F* FOUR F@ F* F- ZERO F@ F= AND
	TWOFORTY F@ FIVE F@ F/ FOUR F@ THREE F@ F* FOUR F@ F* F- ZERO F@ F= AND
	S" 5 != 4+1, 240/3 != 80, 240/4 != 60, OR 240/5 != 48"
	TSTCOND

	ERRCNT{ FAILURE } @ 0=  IF
		." -1, 0, 1/2, 1, 2, 3, 4, 5, 9, 27, 32 & 240 ARE O.K." CR
		CR
	THEN
	." SEARCHING FOR RADIX AND PRECISION." CR
	ONE F@ W F!
	BEGIN
		W F@ W   F@ F+ W F!
		W F@ ONE F@ F+ Y F!
		Y F@ W   F@ F- Z F!
		Z F@ ONE F@ F- Y F!
	MINUSONE F@  Y F@ FABS F+  ZERO F@ F<  WHILE
	REPEAT
 
	\ .. NOW W IS JUST BIG ENOUGH THAT |((W+1)-W)-1| >= 1 ...
	ZERO F@ PRECISIONF F!
	ONE F@ Y F!
	BEGIN
		W F@  Y F@ F+  RADIX F!
		Y F@  Y F@ F+  Y F!
		RADIX F@  W F@ F-  RADIX F!
	RADIX F@ ZERO F@ F=  WHILE
	REPEAT

	RADIX F@ TWO F@ F< IF  ONE F@ RADIX F!  THEN
	." RADIX = " RADIX F@ F. ." ." CR
	RADIX F@ 1E F<> IF
		ONE F@ W F!
		BEGIN
			PRECISIONF F@ ONE F@ F+ PRECISIONF F!
			W F@ RADIX F@ F* W F!
			W F@ ONE F@ F+  Y F!
		Y F@ W F@ F- ONE F@ F=  WHILE
		REPEAT
	THEN
	\ ... NOW W == RADIX^PRECISION IS BARELY TOO BIG TO SATISFY (W+1)-W == 1
	\		                              ...
	ONE F@ W F@ F/     U1 F!
	RADIX F@ U1 F@ F*  U2 F!
	." CLOSEST RELATIVE SEPARATION FOUND IS U1 = " U1 F@ FS. ( %.7E) CR CR
	." RECALCULATING RADIX AND PRECISION " CR

	\ SAVE OLD VALUES
	RADIX F@ E0 F!
	U1 F@    E1 F!
	U2 F@    E9 F!
	PRECISIONF F@ E3 F!

	FOUR F@ THREE F@ F/ X F!
	X F@ ONE F@ F- THIRD F!
	HALF F@  THIRD F@ F- F6 F!
	F6 F@ F6 F@ F+ X F!
	X F@ THIRD F@ F- FABS X F!
	X F@ U2 F@ F<  IF  U2 F@ X F!  THEN

	\ ... NOW X = (UNKNOWN NO.) ULPS OF 1+...
	BEGIN
		X F@ U2 F!
		HALF F@ U2 F@ F* THIRTYTWO F@ U2 F@ F* U2 F@ F* F+ Y F!
		ONE F@ Y F@ F+ Y F!
		Y F@ ONE F@ F- X F!
	U2 F@ X F@ F<=  X F@ ZERO F@ F<=  OR INVERT WHILE
	REPEAT

	\ ... NOW U2 == 1 ULP OF 1 + ...
	TWO F@ THREE F@ F/ X F!
	X F@ HALF F@ F- F6 F!
	F6 F@ F6 F@ F+ THIRD F!
	THIRD F@ HALF F@ F- X F!
	X F@ F6 F@ F+ FABS X F!
	X F@ U1 F@ F< IF U1 F@ X F! THEN

	\ ... NOW  X == (UNKNOWN NO.) ULPS OF 1 -...
	BEGIN
		X F@ U1 F!
		HALF F@ U1 F@ F* THIRTYTWO F@ U1 F@ F* U1 F@ F* F+ Y F!
		HALF F@ Y F@ F- Y F!
		HALF F@ Y F@ F+ X F!
		HALF F@ X F@ F- Y F!
		HALF F@ Y F@ F+ X F!
	U1 F@ X F@ F<=  X F@ ZERO F@ F<= OR INVERT WHILE
	REPEAT
	\ ... NOW U1 == 1 ULP OF 1 - ...
	U1 F@ E1 F@ F= IF 
		." CONFIRMS CLOSEST RELATIVE SEPARATION U1 ." CR
	ELSE 
		." GETS BETTER CLOSEST RELATIVE SEPARATION U1 = " U1 F@ FS. ( %.7E) CR
	THEN
	ONE F@ U1 F@ F/ W F!
	HALF F@ U1 F@ F- HALF F@ F+ F9 F!
	0.01E U2 F@ U1 F@ F/ F+ FLOOR RADIX F!
	RADIX F@ E0 F@ F=  IF
		." RADIX CONFIRMED." CR
	ELSE 
		." MYSTERY: RECALCULATED RADIX = " ( %.7E) RADIX F@ FS. CR
	THEN

	DEFECT
	RADIX F@  EIGHT F@ EIGHT F@ F+ F<=
	S" RADIX IS TOO BIG: ROUNDOFF PROBLEMS"
	TSTCOND

	FLAW
	RADIX F@ TWO F@ F=
	RADIX F@ 10E F= OR
	RADIX F@ ONE F@ F= OR
	S" RADIX IS NOT AS GOOD AS 2 OR 10"
	TSTCOND
	\ =============================================
	20 MILESTONE !
	\ =============================================
	
	FAILURE
	F9 F@ HALF F@ F-  HALF F@ F<
	S" (1-U1)-1/2 < 1/2 IS FALSE, PROG. FAILS?"
	TSTCOND

	F9 F@ X F!
	1 IVAR !
	X F@ HALF F@ F- Y F!
	Y F@ HALF F@ F- Z F!

	FAILURE
	X F@ ONE F@ F<>  Z F@ ZERO F@ F= OR
	S" COMPARISON IS FUZZY,X=1 BUT X-1/2-1/2 != 0"
	TSTCOND

	ONE F@ U2 F@ F+ X F!
	0 IVAR !
	\ =============================================
	25 MILESTONE !
	\ =============================================
	\ ... BMINUSU2 = NEXTAFTER(RADIX, 0)
	RADIX F@ ONE F@ F- BMINUSU2 F!
	BMINUSU2 F@ U2 F@ F- ONE F@ F+ BMINUSU2 F!
	\ PURIFY INTEGERS
	RADIX F@ ONE F@ F<> IF
		TWOFORTY F@ U1 F@ FLN F* RADIX F@ FLN F/ FNEGATE X F!
		HALF F@  X F@ F+ FLOOR Y F!
		X F@ Y F@ F- FABS FOUR F@ F* ONE F@ F<  IF Y F@ X F! THEN
		X F@ TWOFORTY F@ F/ PRECISIONF F!
		HALF F@ PRECISIONF F@ F+ FLOOR Y F!
		PRECISIONF F@ Y F@ F- FABS TWOFORTY F@ F* HALF F@ F< IF Y F@ PRECISIONF F! THEN
	THEN
	PRECISIONF F@ FLOOR PRECISIONF F@ F<>   RADIX F@ ONE F@ F= OR IF
		." PRECISION CANNOT BE CHARACTERIZED BY AN INTEGER NUMBER" CR
		." OF SIGNIFICANT DIGITS BUT, BY ITSELF, THIS IS A MINOR FLAW." CR
	THEN
	RADIX F@ ONE F@ F=  IF
		." LOGARITHMIC ENCODING HAS PRECISION CHARACTERIZED SOLELY BY U1." CR
	ELSE 
		." THE NUMBER OF SIGNIFICANT DIGITS OF THE RADIX IS " PRECISIONF F@ F.
		CR
	THEN

	SERIOUS
	U2 F@ NINE F@ F* NINE F@ F* TWOFORTY F@ F* ONE F@ F<
	S" PRECISION WORSE THAN 5 DECIMAL FIGURES  "
	TSTCOND
	\ =============================================
	30 MILESTONE !
	\ =============================================
	\ TEST FOR EXTRA-PRECISE SUBEPRESSIONS
	\ X = FABS(((FOUR / THREE - ONE) - ONE / FOUR) * THREE - ONE / FOUR);
	FOUR F@ THREE F@ F/  ONE F@ F-  ONE F@ FOUR F@ F/ F-
	THREE F@ F*  ONE F@ FOUR F@ F/ F- FABS  X F!
	BEGIN
		X F@ Z2 F!
		\ X = (ONE + (HALF * Z2 + THIRTYTWO * Z2 * Z2)) - ONE;
		HALF F@ Z2 F@ F* THIRTYTWO F@ Z2 F@ F* Z2 F@ F* F+
		ONE F@ F+  ONE F@ F- X F!
	Z2 F@ X F@ F<=   X F@ ZERO F@ F<= OR INVERT	WHILE
	REPEAT

	\ X = Y = Z = FABS((THREE / FOUR - TWO / THREE) * THREE - ONE / FOUR);
	THREE F@ FOUR F@ F/  TWO F@ THREE F@ F/ F-
	THREE F@ F*  ONE F@ FOUR F@ F/ F- FABS
	FDUP Z F! FDUP Y F! X F!
	BEGIN
		Z F@ Z1 F!
		\ Z = (ONE / TWO - ((ONE / TWO - (HALF * Z1 + THIRTYTWO * Z1 * Z1))
		\ 	+ ONE / TWO)) + ONE / TWO;
		HALF F@ Z1 F@ F*  THIRTYTWO F@ Z1 F@ F* Z1 F@ F* F+
		ONE F@ TWO F@ F/ FSWAP F-
		ONE F@ TWO F@ F/ F+
		ONE F@ TWO F@ F/ F-
		ONE F@ TWO F@ F/ F+  Z F!
	Z1 F@ Z F@ F<=  Z F@ ZERO F@ F<= OR INVERT  WHILE
	REPEAT
 
	BEGIN
		BEGIN
			Y F@ Y1 F!
			\ Y = (HALF - ((HALF - (HALF * Y1 + THIRTYTWO * Y1 * Y1)) + HALF
			\ 	)) + HALF;
			HALF F@ Y1 F@ F* THIRTYTWO F@ Y1 F@ F* Y1 F@ F* F+
			HALF F@ FSWAP F-  HALF F@ F+
			HALF F@ FSWAP F-  HALF F@ F+  Y F!
		Y1 F@ Y F@ F<=   Y F@ ZERO F@ F<= OR INVERT WHILE
		REPEAT 
		X F@ X1 F!
		\ X = ((HALF * X1 + THIRTYTWO * X1 * X1) - F9) + F9;
		HALF F@ X1 F@ F* THIRTYTWO F@ X1 F@ F* X1 F@ F* F+
		F9 F@ F-  F9 F@ F+  X F!
	X1 F@ X F@ F<=   X F@ ZERO F@ F<= OR INVERT WHILE
	REPEAT
 
	X1 F@ Y1 F@ F<>   X1 F@ Z1 F@ F<> OR IF
		SERIOUS S" DISAGREEMENTS AMONG THE VALUES X1, Y1, Z1" BADCOND
		." RESPECTIVELY  " X1 F@ FS. ( %.7E)  Y1 F@ FS. ( %.7E) Z1 F@ FS. ( %.7E) CR
		." ARE SYMPTOMS OF INCONSISTENCIES INTRODUCED" CR
		." BY EXTRA-PRECISE EVALUATION OF ARITHMETIC SUBEXPRESSIONS." CR
		S" POSSIBLY SOME PART OF THIS" NOTIFY
		X1 F@ U1 F@ F=  Y1 F@ U1 F@ F= OR  Z1 F@ U1 F@ F= OR IF
			." THAT FEATURE IS NOT TESTED FURTHER BY THIS PROGRAM." CR
		THEN
	ELSE
		Z1 F@ U1 F@ F<>   Z2 F@ U2 F@ F<> OR IF
			Z1 F@ U1 F@ F>=  Z2 F@ U2 F@ F>= OR IF
				FAILURE S" " BADCOND
				S" PRECISION" NOTIFY
				."    U1 = " U1 F@  FS. ( %.7E)
				." Z1 - U1 = " Z1 F@ U1 F@ F- FS. ( %.7E) CR
				."    U2 = " U2 F@  FS. ( %.7E)
				." Z2 - U2 = " Z2 F@ U2 F@ F-  FS. ( %.7E) CR
			ELSE
				Z1 F@ ZERO F@ F<=   Z2 F@ ZERO F@ F<= OR IF
					." BECAUSE OF UNUSUAL RADIX = " RADIX F@ F.
					." , OR EXACT RATIONAL ARITHMETIC A RESULT" CR
					." Z1 = "  Z1 F@ FS. ( %.7E) ." OR Z2 = " Z2 F@ FS. ( %.7E)
					S" OF AN EXTRA-PRECISION" NOTIFY CR
				THEN
				Z1 F@ Z2 F@ F<>   Z1 F@ ZERO F@ F> OR IF
					Z1 F@ U1 F@ F/ X F!
					Z2 F@ U2 F@ F/ Y F!
					Y F@  X F@ F>  IF Y F@ X F! THEN
					X F@ FLN FNEGATE Q F!
					." SOME SUBEXPRESSIONS APPEAR TO BE CALCULATED EXTRA" CR
					." PRECISELY WITH ABOUT " Q F@ RADIX F@ FLN F/ ( %G) F. ." EXTRA B-DIGITS, I.E." CR
						
					." ROUGHLY " Q F@ 10E FLN F/ ( %G) F. ." EXTRA SIGNIFICANT DECIMALS." CR
						
				THEN
				." THAT FEATURE IS NOT TESTED FURTHER BY THIS PROGRAM." CR
			THEN
		THEN
	THEN
	PAUSE
;
\ END OF PART2

: PART3 ( -- )
	\ =============================================
	35 MILESTONE !
	\ =============================================
	RADIX F@ TWO F@ F>= IF
		W F@  RADIX F@ RADIX F@ F* F/  X F!
		X F@ ONE F@ F+  Y F!
		Y F@ X F@ F-    Z F!
		Z F@ U2 F@ F+   T F!
		T F@ Z F@ F-    X F!

		FAILURE  X F@ U2 F@ F=  S" SUBTRACTION IS NOT NORMALIZED X=Y,X+Z != Y+Z!"
		TSTCOND

		X F@ U2 F@ F=  IF 
			." SUBTRACTION APPEARS TO BE NORMALIZED, AS IT SHOULD BE."
		THEN
	THEN

	CR ." CHECKING FOR GUARD DIGIT IN F*, F/, AND F-." CR
	F9 F@ ONE F@ F*    Y F!
	ONE F@ F9 F@ F*    Z F!
	F9 F@ HALF F@ F-   X F!
	Y F@ HALF F@ F- X F@ F-    Y F!
	Z F@ HALF F@ F- X F@ F-    Z F!
	ONE F@ U2 F@ F+    X F!
	X F@ RADIX F@ F*   T F!
	RADIX F@ X F@ F*   R F!
	T F@ RADIX F@ F-   X F!
	X F@ RADIX F@  U2 F@ F* F- X F!
	R F@ RADIX F@ F-   T F!
	T F@ RADIX F@  U2 F@ F* F- T F!
	X F@ RADIX F@ ONE F@ F- F* X F!
	T F@ RADIX F@ ONE F@ F- F* T F!

	X F@ ZERO F@ F=       Y F@ ZERO F@ F=  AND
	Z F@ ZERO F@ F=  AND  T F@ ZERO F@ F=  AND  IF
		YES GMULT !
	ELSE
		NO GMULT !
		SERIOUS  FALSE  S" F* LACKS A GUARD DIGIT, SO 1*X != X"
		TSTCOND
	THEN
	RADIX F@ U2 F@ F* Z F!
	ONE F@ Z F@ F+    X F!
	X F@ Z F@ F+   X F@ X F@ F* F- FABS U2 F@ F-  Y F!
	ONE F@ U2 F@ F-   X F!
	X F@ U2 F@ F-  X F@ X F@ F* F- FABS U1 F@ F-  Z F!

	FAILURE  Y F@ ZERO F@ F<=   Z F@ ZERO F@ F<=  AND
	S" F* GETS TOO MANY FINAL DIGITS WRONG."
	TSTCOND

	ONE F@ U2 F@ F- Y F!
	ONE F@ U2 F@ F+ X F!
	ONE F@ Y F@ F/  Z F!
	Z F@ X F@ F-    Y F!
	ONE F@ THREE F@ F/        X F!
	THREE F@ NINE F@ F/   Z F!
	X F@ Z F@ F-    X F!
	NINE F@ TWENTYSEVEN F@ F/ T F!
	Z F@ T F@ F-    Z F!
	
	DEFECT  X F@ ZERO F@ F=   Y F@ ZERO F@ F=  AND  Z F@ ZERO F@ F= AND
	S" DIVISION LACKS A GUARD DIGIT, SO ERROR CAN EXCEED 1 ULP\NOR  1/3  AND  3/9  AND  9/27 MAY DISAGREE"
	TSTCOND

	F9 F@  ONE F@ F/ Y F!
	F9 F@ HALF F@ F- X F!
	Y  F@ HALF F@ F- X F@ F- Y F!
	ONE F@  U2 F@ F+ X F!
	X  F@  ONE F@ F/ T F!
	T  F@    X F@ F- X F!
	X F@ ZERO F@ F=   Y F@ ZERO F@ F= AND   Z F@ ZERO F@ F= AND IF
		YES GDIV !
	ELSE
		NO GDIV !

		SERIOUS  FALSE  S" DIVISION LACKS A GUARD DIGIT, SO X/1 != X"
		TSTCOND
	THEN
	ONE F@  ONE  F@ U2 F@ F+  F/  X F!
	X   F@  HALF F@ F- HALF F@ F- Y F!
	
	SERIOUS  Y F@ ZERO F@ F<  S" COMPUTED VALUE OF 1/1.000..1 >= 1"
	TSTCOND

	ONE F@ U2 F@ F- X F!
	ONE F@ RADIX F@ U2 F@ F*  F+  Y F!
	X F@ RADIX F@ F* Z F!
	Y F@ RADIX F@ F* T F!
	Z F@ RADIX F@ F/ R F!
	T F@ RADIX F@ F/ STICKYBIT F!
	R F@ X F@ F- X F!
	STICKYBIT F@ Y F@ F- Y F!

	FAILURE  X F@ ZERO F@ F=   Y F@ ZERO F@ F=  AND
	S" F* AND/OR F/ GETS TOO MANY LAST DIGITS WRONG"
	TSTCOND

	ONE F@ U1 F@ F- Y F!
	ONE F@ F9 F@ F- X F!
	ONE F@  Y F@ F- Y F!
	RADIX F@ U2 F@ F- T F!
	RADIX F@ BMINUSU2 F@ F- Z F!
	RADIX F@ T F@ F-  T F!
	X F@ U1 F@ F=   Y F@ U1 F@ F= AND  Z F@ U2 F@ F= AND  T F@ U2 F@ F= AND IF
		YES GADDSUB !
	ELSE
		NO GADDSUB !
		SERIOUS  FALSE  S" F- LACKS GUARD DIGIT, SO CANCELLATION IS OBSCURED"
		TSTCOND
	THEN
	F9 F@ ONE F@ F<>   F9 F@ ONE F@ F- ZERO F@ F>=  AND IF
		SERIOUS S" COMPARISON ALLEGES  (1-U1) < 1  ALTHOUGH " BADCOND
		."  SUBTRACTION YIELDS  (1-U1) - 1 = 0 , THEREBY VITIATING" CR
		."  SUCH PRECAUTIONS AGAINST DIVISION BY ZERO AS" CR
		."  ...  IF (X == 1.0) {.....} ELSE {.../(X-1.0)...}" CR
	THEN
	YES GMULT @ =   YES GDIV @ = AND  YES GADDSUB @ = AND IF
		."     F*, F/, AND F- APPEAR TO HAVE GUARD DIGITS, AS THEY SHOULD." CR
	THEN
	\ =============================================
	40 MILESTONE !
	\ =============================================
	PAUSE
	." CHECKING ROUNDING ON MULTIPLY, DIVIDE AND ADD/SUBTRACT." CR
	OTHER RMULT !
	OTHER RDIV  !
	OTHER RADDSUB !
	RADIX F@ TWO F@ F/  RADIXD2 F!
	TWO F@ A1 F!
	FALSE DONE !
	BEGIN
		RADIX F@ AINVRSE F!
		BEGIN
			AINVRSE F@ X F!
			AINVRSE F@ A1 F@ F/ AINVRSE F!
		AINVRSE F@ FLOOR AINVRSE F@ F<> INVERT WHILE
		REPEAT
		X F@ ONE F@ F=   A1 F@ THREE F@ F>  OR DONE !
		DONE @ INVERT IF  NINE F@ ONE F@ F+  A1 F! THEN
	DONE @ INVERT WHILE
	REPEAT
	X F@ ONE F@ F=  IF RADIX F@ A1 F! THEN
	ONE F@ A1 F@ F/  AINVRSE F!
	A1 F@  X F!
	AINVRSE F@ Y F!
	FALSE DONE !
	BEGIN
		X F@ Y F@ F* HALF F@ F- Z F!
		FAILURE  Z F@ HALF F@ F=  S" X * (1/X) DIFFERS FROM 1" TSTCOND
		X F@ RADIX F@ F= DONE !
		RADIX F@ X F!
		ONE F@ X F@ F/ Y F!
	DONE @ INVERT WHILE
	REPEAT
	ONE F@ U2 F@ F+ Y2 F!
	ONE F@ U2 F@ F- Y1 F!
	ONEANDHALF F@ U2 F@ F- X F!
	ONEANDHALF F@ U2 F@ F+ Y F!
	X F@ U2 F@ F- Y2 F@ F* Z F!
	Y F@ Y1 F@ F* T F!
	Z F@  X F@ F- Z F!
	T F@  X F@ F- T F!
	X F@ Y2 F@ F* X F!
	Y F@ U2 F@ F+ Y1 F@ F* Y F!
	X F@ ONEANDHALF F@ F- X F!
	Y F@ ONEANDHALF F@ F- Y F!
	X F@ ZERO F@ F=   Y F@ ZERO F@ F= AND  Z F@ ZERO F@ F= AND  T F@ ZERO F@ F<= AND IF
		ONEANDHALF F@  U2 F@ F+  Y2 F@ F*  X F!
		ONEANDHALF F@  U2 F@ F-  U2 F@ F-  Y F!
		ONEANDHALF F@  U2 F@ F+  U2 F@ F+  Z F!
		ONEANDHALF F@  U2 F@ F-  Y1 F@ F*  T F!
		X F@   Z F@ U2 F@ F+ F-  X F!
		Y F@  Y1 F@ F*  STICKYBIT F!
		Z F@  Y2 F@ F*  S F!
		T F@   Y F@ F-  T F!
		U2 F@ Y F@ F- STICKYBIT F@ F+ Y F!
		S F@  Z F@ U2 F@ F+ U2 F@ F+ F- Z F!
		Y2 F@  U2 F@ F+  Y1 F@ F*  STICKYBIT F!
		Y2 F@ Y1 F@ F* Y1 F!
		STICKYBIT F@  Y2 F@ F-  STICKYBIT F!
		Y1 F@  HALF F@ F- Y1 F!
		X F@ ZERO F@ F=      Y F@ ZERO F@ F= AND  Z F@ ZERO F@ F= AND
		T F@ ZERO F@ F= AND  STICKYBIT F@ ZERO F@ F= AND  Y1 F@ HALF F@ F= AND IF
			ROUNDED RMULT !
			." MULTIPLICATION APPEARS TO ROUND CORRECTLY." CR

		ELSE
			X F@ U2 F@ F+ ZERO F@ F=
			Y F@ ZERO F@ F< AND
			Z F@ U2 F@ F+ ZERO F@ F= AND
			T F@ ZERO F@ F< AND
		        STICKYBIT F@ U2 F@ F+ ZERO F@ F= AND
			Y1 F@ HALF F@ F< AND IF
				CHOPPED RMULT !
				." MULTIPLICATION APPEARS TO CHOP." CR
			ELSE
			 	." F* IS NEITHER CHOPPED NOR CORRECTLY ROUNDED." CR
				RMULT @ ROUNDED =   GMULT @ NO =  AND IF
					S" MULTIPLICATION" NOTIFY
				THEN
			THEN
		THEN
	ELSE 
		." F* IS NEITHER CHOPPED NOR CORRECTLY ROUNDED." CR ( ABORT)
	THEN
	\ =============================================
	45 MILESTONE !
	\ =============================================
	ONE F@ U2 F@ F+ Y2 F!
	ONE F@ U2 F@ F- Y1 F!
	ONEANDHALF F@ U2 F@ F+ U2 F@ F+  Z F!
	Z F@ Y2 F@ F/ X F!
	ONEANDHALF F@ U2 F@ F- U2 F@ F-  T F!
	T F@ U2 F@ F-  Y1 F@ F/  Y F!
	Z F@ U2 F@ F+  Y2 F@ F/  Z F!
	X F@   ONEANDHALF F@ F-  X F!
	Y F@  T F@ F-  Y F!
	T F@ Y1 F@ F/  T F!
	Z F@  ONEANDHALF F@ U2 F@ F+ F- Z F!
	U2 F@ ONEANDHALF F@ F-  T F@ F+ T F!

	X F@ ZERO F@ F>     Y F@ ZERO F@ F> OR
	Z F@ ZERO F@ F> OR  T F@ ZERO F@ F> OR  INVERT IF
		ONEANDHALF F@  Y2 F@ F/  X F!
		ONEANDHALF F@  U2 F@ F-  Y F!
		ONEANDHALF F@  U2 F@ F+  Z F!
		X F@   Y F@ F-  X F!
		ONEANDHALF F@  Y1 F@ F/  T F!
		Y F@  Y1 F@ F/  Y F!
		T F@   Z F@ U2 F@ F+ F-  T F!
		Y F@   Z F@ F- Y F!
		Z F@  Y2 F@ F/ Z F!
		Y2 F@ U2 F@ F+ Y2 F@ F/  Y1 F!
		Z F@   ONEANDHALF F@ F-  Z F!
		Y1 F@ Y2 F@ F- Y2 F!
		F9 F@ U1 F@ F- F9 F@ F/  Y1 F!
		X F@ ZERO F@ F=      Y  F@ ZERO F@ F= AND  Z  F@ ZERO F@ F= AND
		T F@ ZERO F@ F= AND  Y2 F@ ZERO F@ F= AND  Y2 F@ ZERO F@ F= AND
		Y1 F@ HALF F@ F- F9 F@ HALF F@ F- F= AND IF
			ROUNDED RDIV !
			." DIVISION APPEARS TO ROUND CORRECTLY." CR
			GDIV @ NO =  IF  S" DIVISION" NOTIFY  THEN

		ELSE
			X  F@ ZERO F@ F<      Y F@ ZERO F@ F< AND
			Z  F@ ZERO F@ F< AND  T F@ ZERO F@ F< AND
			Y2 F@ ZERO F@ F< AND
			Y1 F@ HALF F@ F- F9 F@ HALF F@ F- F< AND IF
				CHOPPED RDIV !
				." DIVISION APPEARS TO CHOP." CR
			THEN
		THEN
	THEN
	RDIV @ OTHER = IF ." F/ IS NEITHER CHOPPED NOR CORRECTLY ROUNDED." CR THEN
	ONE F@ RADIX F@ F/ BINVRSE F!

	FAILURE
	BINVRSE F@ RADIX F@ F* HALF F@ F- HALF F@ F=
	S" RADIX * ( 1 / RADIX ) DIFFERS FROM 1"
	TSTCOND
;
\ END PART3

: PART4_LOOPA ( -- )
	1 IVAR !
	BEGIN
		IVAR @ NOTRIALS @ <= WHILE
		X F@ ONE F@ F+ X F!
		DEFECT SQXMINX
		JVAR F@  ZERO F@ F> IF EXIT THEN
		1 IVAR +!
	REPEAT
;


: PART4 ( -- )
	\ =============================================
	50 MILESTONE !
	\ =============================================
	FAILURE
	F9 F@ U1 F@ F+ HALF F@ F- HALF F@ F=
	BMINUSU2 F@ U2 F@ F+ ONE F@ F- RADIX F@ ONE F@ F- F= AND
	S" INCOMPLETE CARRY-PROPAGATION IN ADDITION"
	TSTCOND

	ONE F@  U1 F@ U1 F@ F* F- X F!
	ONE F@ U2 F@ ONE F@  U2 F@ F- F* F+ Y F!
	F9 F@ HALF F@ F- Z F!
	X F@ HALF F@ F- Z F@ F- X F!
	Y F@ ONE F@ F- Y F!
	X F@ ZERO F@ F=   Y F@ ZERO F@ F=  AND IF
		CHOPPED RADDSUB !
		." ADD/SUBTRACT APPEARS TO BE CHOPPED." CR
	THEN
	GADDSUB @ YES = IF
		HALF F@  U2 F@  F+  U2 F@  F*  X F!
		HALF F@  U2 F@  F-  U2 F@  F*  Y F!
		ONE F@  X F@ F+  X F!
		ONE F@  Y F@ F+  Y F!
		ONE F@  U2 F@ F+  X F@ F- X F!
		ONE F@  Y F@ F- Y F!
		X F@ ZERO F@ F=  Y F@ ZERO F@ F=  AND IF
			HALF F@ U2 F@ F+  U1 F@ F*  X F!
			HALF F@ U2 F@ F-  U1 F@ F*  Y F!
			ONE F@  X F@ F-  X F!
			ONE F@  Y F@ F-  Y F!
			F9  F@  X F@ F-  X F!
			ONE F@  Y F@ F-  Y F!
			X F@ ZERO F@ F=   Y F@ ZERO F@ F=  AND IF
				ROUNDED RADDSUB !
				." ADDITION/SUBTRACTION APPEARS TO ROUND CORRECTLY." CR
				GADDSUB @ NO = IF  S" ADD/SUBTRACT" NOTIFY  THEN
			ELSE 
				." ADDITION/SUBTRACTION NEITHER ROUNDS NOR CHOPS." CR
			THEN
		ELSE 
			." ADDITION/SUBTRACTION NEITHER ROUNDS NOR CHOPS." CR
		THEN
	ELSE 
		." ADDITION/SUBTRACTION NEITHER ROUNDS NOR CHOPS." CR
	THEN
	ONE F@ S F!
	ONE F@  HALF F@  ONE F@ HALF F@ F+ F* F+  X F!
	ONE F@  U2 F@ F+ HALF F@ F*  Y F!
	X F@  Y F@ F-  Z F!
	Y F@  X F@ F-  T F!
	Z F@  T F@ F+  STICKYBIT F!
	STICKYBIT F@ ZERO F@ F<> IF
		ZERO F@ S F!
		FLAW S" (X - Y) + (Y - X) IS NON ZERO!" BADCOND
	THEN
	ZERO F@ STICKYBIT F!

	GMULT @ YES =   GDIV @ YES = AND   GADDSUB @ YES = AND
	RMULT @ ROUNDED = AND    RDIV @ ROUNDED = AND
	RADDSUB @ ROUNDED = AND  RADIXD2 F@ FLOOR RADIXD2 F@ F= AND  IF
		." CHECKING FOR STICKY BIT." CR
		HALF F@  U1 F@ F+  U2 F@ F*  X F!
		HALF F@  U2 F@ F*  Y F!
		ONE  F@  Y  F@ F+  Z F!
		ONE  F@  X  F@ F+  T F!
		Z F@ ONE F@ F- ZERO F@ F<=   T F@ ONE F@ F- U2 F@ F>=  AND IF
			T F@ Y F@ F+  Z F!
			Z F@ X F@ F-  Y F!
			Z F@ T F@ F- U2 F@ F>=   Y F@ T F@ F- ZERO F@ F=  AND IF
				HALF F@ U1 F@ F+  U1 F@ F*  X F!
				HALF F@ U1 F@ F*  Y F!
				ONE  F@ Y  F@ F-  Z F!
				ONE  F@ X  F@ F-  T F!
				Z F@ ONE F@ F- ZERO F@ F=  T F@ F9 F@ F- ZERO F@ F=  AND IF
					HALF F@ U1 F@ F- U1 F@ F*  Z F!
					F9 F@ Z F@ F-  T F!
					F9 F@ Y F@ F-  Q F!
					T F@ F9 F@ F- ZERO F@ F=
					F9 F@ U1 F@ F- Q F@ F- ZERO F@ F=  AND IF
						ONE F@ U2 F@ F+  ONEANDHALF F@ F* Z F!
						ONEANDHALF F@ U2 F@ F+ Z F@ F- U2 F@ F+  T F!
						ONE F@ HALF F@ RADIX F@ F/ F+  X F!
						ONE F@ RADIX F@ U2 F@ F* F+ Y F!
						X F@ Y F@ F* Z F!
						T F@ ZERO F@ F=
						X F@ RADIX F@ U2 F@ F* F+
						Z F@ F- ZERO F@ F= AND IF
							RADIX F@ TWO F@ F<> IF
								TWO F@ U2 F@ F+ X F!
								X F@ TWO F@ F/ Y F!
								Y F@ ONE F@ F- ZERO F@ F=  IF
									S F@ STICKYBIT F!
								THEN
							ELSE
								S F@ STICKYBIT F!
							THEN
						THEN
					THEN
				THEN
			THEN
		THEN
	THEN
	STICKYBIT F@ ONE F@ F=  IF
		." STICKY BIT APPARENTLY USED CORRECTLY." CR
	ELSE
		." STICKY BIT USED INCORRECTLY OR NOT AT ALL." CR
	THEN

	FLAW
	GMULT @ NO =  GDIV @ NO = OR  GADDSUB @ NO = OR
	RMULT @ OTHER = OR  RDIV @ OTHER = OR  RADDSUB @ OTHER = OR INVERT
	S" LACK(S) OF GUARD DIGITS OR FAILURE(S) TO CORRECTLY ROUND OR CHOP (NOTED ABOVE) COUNT AS ONE FLAW IN THE FINAL TALLY BELOW"
	TSTCOND
	\ =============================================
	60 MILESTONE !
	\ =============================================
	CR
	." DOES MULTIPLICATION COMMUTE?  "
	." TESTING ON " NOTRIALS ? ." RANDOM PAIRS." CR
	3.0E FSQRT RANDOM9 F!
	THIRD F@   RANDOM1 F!
	1 IVAR !
	BEGIN
		RANDOM X F!
		RANDOM Y F!
		Y F@ X F@ F*  Z9 F!
		X F@ Y F@ F*  Z F!
		Z F@ Z9 F@ F- Z9 F!
		1 IVAR +!
	IVAR @  NOTRIALS @ >   Z9 F@ ZERO F@ F<>  OR INVERT WHILE
	REPEAT 
	IVAR @ NOTRIALS @ = IF
		ONE F@  HALF F@ THREE F@ F/ F+ RANDOM1 F!
		U2 F@ U1 F@ F+ ONE F@ F+ RANDOM2 F!
		RANDOM1 F@ RANDOM2 F@ F* Z F!
		RANDOM2 F@ RANDOM1 F@ F* Y F!
		\ Z9 = (ONE + HALF / THREE) * ((U2 + U1) + ONE) - (ONE + HALF /
		\	THREE) * ((U2 + U1) + ONE)
		ONE F@ HALF F@ THREE F@ F/ F+  U2 F@ U1 F@ F+ ONE F@ F+ F*
		ONE F@ HALF F@ THREE F@ F/ F+  U2 F@ U1 F@ F+ ONE F@ F+ F* F- Z9 F!
	THEN
	IVAR @ NOTRIALS @ =   Z9 F@ ZERO F@ F= OR  INVERT IF
		DEFECT S" X * Y == Y * X TRIAL FAILS." BADCOND
	ELSE 
		."     NO FAILURES FOUND IN " NOTRIALS ? ." INTEGER PAIRS." CR
	THEN
	\ =============================================
	70 MILESTONE !
	\ =============================================
	CR ." RUNNING TEST OF SQUARE ROOT(X)." CR

	FAILURE
	ZERO F@  ZERO F@ FSQRT F=
	ZERO F@ FNEGATE  ZERO F@ FNEGATE FSQRT F= AND
	ONE F@ ONE F@ FSQRT F= AND
	S" SQUARE ROOT OF 0.0, -0.0 OR 1.0 WRONG"
	TSTCOND

	ZERO F@ MINSQER F!
	ZERO F@ MAXSQER F!
	ZERO F@ JVAR F!
	RADIX F@  X F!
	U2 F@ ONEULP F!
	SERIOUS SQXMINX
	BINVRSE F@ X F!
	BINVRSE F@ U1 F@ F* ONEULP F!
	SERIOUS SQXMINX
	U1 F@ X F!
	U1 F@ U1 F@ F* ONEULP F!
	SERIOUS SQXMINX
	JVAR F@ ZERO F@ F<> IF  PAUSE  THEN
	." TESTING IF SQRT(X * X) == X FOR " NOTRIALS ? ." INTEGERS X." CR
	ZERO F@ JVAR F!
	TWO F@ X F!
	RADIX F@ Y F!
	RADIX F@ ONE F@ F<> IF
		BEGIN
			Y F@ X F!
			RADIX F@ Y F@ F* Y F!
			Y F@ X F@ F-  NOTRIALS @ S>F F>= INVERT WHILE
		REPEAT
	THEN
	X F@ U2 F@ F* ONEULP F!
	PART4_LOOPA

	." TEST FOR SQRT MONOTONICITY."
	1 NEGATE IVAR !
	BMINUSU2 F@ X F!
	RADIX F@    Y F!
	RADIX F@  RADIX F@ U2 F@ F* F+ Z F!
	FALSE NOTMONOT !
	FALSE MONOT !
	BEGIN
		NOTMONOT @  MONOT @ OR INVERT WHILE
		1 IVAR +!
		X F@ FSQRT X F!
		Y F@ FSQRT Q F!
		Z F@ FSQRT Z F!
		X F@ Q F@ F>  Q F@ Z F@ F>  OR IF
			TRUE NOTMONOT !
		ELSE
			Q F@ HALF F@ F+ FLOOR  Q F!
			IVAR @ 0>  RADIX F@ Q F@ Q F@ F* F=  OR INVERT IF
				TRUE MONOT !
			ELSE 
				IVAR @ 0> IF
					IVAR @ 1 > IF
						TRUE MONOT !
					ELSE
						Y F@ BINVRSE F@ F* Y F!
						Y F@ U1 F@ F- X F!
						Y F@ U1 F@ F+ Z F!
					THEN
				ELSE
					Q F@ Y F!
					Y F@ U2 F@ F- X F!
					Y F@ U2 F@ F+ Z F!
				THEN
			THEN
		THEN
	REPEAT
	MONOT @ IF
		CR ." SQRT HAS PASSED A TEST FOR MONOTONICITY." CR
	ELSE
		DEFECT S" " BADCOND
		CR ." SQRT(X) IS NON-MONOTONIC FOR X NEAR " Y F@ F. ( %.7E) CR
	THEN

;
\ END PART4

: PART5 ( -- )
	\ =============================================
	80 MILESTONE !
	\ =============================================
	MINSQER F@ HALF F@ F+ MINSQER F!
	MAXSQER F@ HALF F@ F- MAXSQER F!
	ONE F@ U2 F@ F+ FSQRT ONE F@ F- U2 F@ F/  Y F!
	Y F@ ONE F@ F-  U2 F@ EIGHT F@ F/ F+ SQER F!
	SQER F@ MAXSQER F@ F> IF  SQER F@  MAXSQER F! THEN
	Y F@  U2 F@ EIGHT F@ F/  F+  SQER F!
	SQER F@ MINSQER F@ F< IF  SQER F@ MINSQER F!  THEN
	F9 F@ FSQRT U2 F@ F-  ONE F@ U2 F@ F- F- U1 F@ F/  Y F!
	Y F@  U1 F@ EIGHT F@ F/  F+  SQER F!
	SQER F@ MAXSQER F@ F> IF  SQER F@ MAXSQER F!  THEN
	Y F@ ONE F@ F+  U1 F@ EIGHT F@ F/  F+  SQER F!
	SQER F@ MINSQER F@ F< IF  SQER F@ MINSQER F!  THEN
	U2 F@ ONEULP F!
	ONEULP F@ X F!
	\ FOR( INDX = 1; INDX <= 3; ++INDX) {
	4 1 DO
		X F@ U1 F@ F+ X F@ F+  F9 F@ F+ FSQRT  Y F!
		Y F@ U2 F@ F-  ONE F@ U2 F@ F- X F@ F+  F-  ONEULP F@ F/  Y F!
		U1 F@ X F@ F- F9 F@ F+  HALF F@ F* X F@ F* X F@ F* ONEULP F@ F/ Z F!
		Y F@ HALF F@ F+  Z F@ F+  SQER F!
		SQER F@ MINSQER F@ F< IF  SQER F@ MINSQER F!  THEN
		Y F@  HALF F@ F- Z F@ F+  SQER F!
		SQER F@ MAXSQER F@ F> IF  SQER F@ MAXSQER F!  THEN
		I 1 =  I 3 =  OR IF
			\ X = ONEULP * SIGN (X) * FLOOR(EIGHT / (NINE * SQRT(ONEULP)))
	ONEULP F@ X F@ SIGN F* EIGHT F@ NINE F@  ONEULP F@ FSQRT F* F/ FLOOR F* X F!
		ELSE
			U1 F@  ONEULP F!
			ONEULP F@ FNEGATE X F!
		THEN
	LOOP
	\ =============================================
	85 MILESTONE !
	\ =============================================
	FALSE SQRWRNG !
	FALSE ANOMALY !
	OTHER RSQRT !  \ ~DGH
	RADIX F@  ONE F@ F<> IF
		." TESTING WHETHER SQRT IS ROUNDED OR CHOPPED." CR
		\ D = FLOOR(HALF + POW(RADIX, ONE + PRECISIONF - FLOOR(PRECISIONF)));
	HALF F@  RADIX F@  ONE F@ PRECISIONF F@ F+ PRECISIONF F@ FLOOR F- POW F+ FLOOR D F!
	\ ... == RADIX^(1 + FRACT) IF (PRECISIONF == INTEGER + FRACT.
		D F@ RADIX F@ F/ X F!
		D F@ A1 F@ F/ Y F!
		X F@ X F@ FLOOR F<>   Y F@ Y F@ FLOOR F<>  OR IF
			TRUE ANOMALY !
		ELSE
			ZERO F@   X F!
			X    F@  Z2 F!
			ONE  F@   Y F!
			Y    F@  Y2 F!
			RADIX F@ ONE F@ F- Z1 F!
			FOUR F@ D F@ F* FOURD F!
			BEGIN
				Y2 F@ Z2 F@ F> IF
					RADIX F@ Q F!
					Y F@ Y1 F!
					BEGIN
						\ X1 = FABS(Q + FLOOR(HALF - Q / Y1) * Y1)
						HALF F@ Q F@ Y1 F@ F/ F- FLOOR Y1 F@ F*
						Q F@ F+ FABS  X1 F!
						Y1 F@ Q F!
						X1 F@ Y1 F!
					X1 F@ ZERO F@ F<= INVERT WHILE
					REPEAT
					Q F@ ONE F@ F<= IF
						Y2 F@ Z2 F!
						 Y F@  Z F!
					THEN
				THEN
				Y  F@ TWO   F@ F+  Y F!
				X  F@ EIGHT F@ F+  X F!
				Y2 F@ X     F@ F+ Y2 F!
				Y2 F@ FOURD F@ F>=  IF  Y2 F@ FOURD F@ F- Y2 F! THEN
			Y F@ D F@ F>=  INVERT WHILE
			REPEAT
			FOURD F@ Z2 F@ F- X8 F!
			X8 F@  Z F@ Z F@ F* F+  FOURD F@ F/  Q F!
			X8 F@ EIGHT F@ F/  X8 F!
			Q F@ Q F@ FLOOR F<> IF
				TRUE ANOMALY !
			ELSE
				FALSE BREAK !
				BEGIN
					Z1 F@ Z F@ F* X F!
					X F@ X F@ RADIX F@ F/ FLOOR RADIX F@ F* F- X F!
					X F@ ONE F@ F= IF
						TRUE BREAK !
					ELSE
						Z1 F@  ONE F@ F- Z1 F!
					THEN
				BREAK @  Z1 F@ ZERO F@ F<=  OR INVERT WHILE
				REPEAT
				Z1 F@ ZERO F@ F<=   BREAK @ INVERT AND IF
					TRUE ANOMALY !
				ELSE
					Z1 F@  RADIXD2 F@ F>  IF Z1 F@ RADIX F@ F- Z1 F! THEN
					BEGIN
						NEWD
					U2 F@ D F@ F*  F9 F@ F>= INVERT WHILE
					REPEAT
					D F@ RADIX F@ F* D F@ F-  W F@ D F@ F- F<> IF
						TRUE ANOMALY !
					ELSE
						D F@ Z2 F!
						0 IVAR !
						D F@  ONE F@ Z F@ F+  HALF F@ F* F+ Y F!
						D F@ Z F@ F+ Q F@ F+ X F!
						SR3750
						D F@ ONE F@ Z F@ F- HALF F@ F* F+ D F@ F+ Y F!
						D F@  Z F@ F-  D F@ F+  X F!
						X F@ Q F@ F+ X F@ F+ X F!
						SR3750
						NEWD
						D F@ Z2 F@ F-  W F@ Z2 F@ F- F<> IF
							TRUE ANOMALY !
						ELSE
							D F@ Z2 F@ F-
							Z2 F@ ONE F@ Z F@ F- HALF F@ F* F+
							F+ Y F!
							D F@ Z2 F@ F- Z2 F@ Z F@ F- Q F@ F+ F+  X F!
							SR3750
							ONE F@ Z F@ F+ HALF F@ F* Y F!
							Q F@ X F!
							SR3750
							IVAR @ 0= IF TRUE ANOMALY ! THEN
						THEN
					THEN
				THEN
			THEN
		THEN
		IVAR @ 0=  ANOMALY @ OR IF
			FAILURE S" ANOMALOUS ARITHMETIC WITH INTEGER < " BADCOND
			." RADIX^PRECISION = " W F@ FS. ( %.7E) CR
			." FAILS TEST WHETHER SQRT ROUNDS OR CHOPS." CR
			TRUE SQRWRNG !
		THEN
	THEN 
	ANOMALY @ INVERT IF
		MINSQER F@ ZERO F@ F<  MAXSQER F@ ZERO F@ F>  OR  INVERT IF
			ROUNDED RSQRT !
			." SQUARE ROOT APPEARS TO BE CORRECTLY ROUNDED." CR
		
		ELSE
			MAXSQER F@ U2 F@ F+  U2 F@ HALF F@ F- F>
			MINSQER F@ HALF F@ F>  OR
			MINSQER F@ RADIX F@ F+ HALF F@ F< OR  IF
				TRUE SQRWRNG !
			ELSE
				CHOPPED RSQRT !
				." SQUARE ROOT APPEARS TO BE CHOPPED." CR
			THEN
		THEN
	THEN
	SQRWRNG @ IF
		." SQUARE ROOT IS NEITHER CHOPPED NOR CORRECTLY ROUNDED." CR
		." OBSERVED ERRORS RUN FROM " MINSQER F@ HALF F@ F- FS. ( %.7E)
		." TO " HALF F@ MAXSQER F@ F+ FS. ( %.7E) ."  ULPS." CR
		SERIOUS  MAXSQER F@ MINSQER F@ F-  RADIX F@ RADIX F@ F*  F<
		S" SQRT GETS TOO MANY LAST DIGITS WRONG"
		TSTCOND
	THEN
	\ =============================================
	90 MILESTONE !
	\ =============================================
	PAUSE
	." TESTING POWERS Z^I FOR SMALL INTEGERS Z AND I." CR
	0 N !
	\ ... TEST POWERS OF ZERO.
	0 IVAR !
	ZERO F@ FNEGATE Z F!
	3 M !
	FALSE BREAK !
	BEGIN
		ONE F@ X F!
		SR3980
		IVAR @ 10 <= IF
			1023 IVAR !
			SR3980
		THEN
		Z F@ MINUSONE F@ F= IF
			TRUE BREAK !
		ELSE
			MINUSONE F@ Z F!
			\ PRINTIFNPOSITIVE
			\ 0 N !
			\ .. IF(-1)^N IS INVALID, REPLACE MINUSONE BY ONE.
			-4 IVAR !
		THEN
	BREAK @ INVERT WHILE
	REPEAT
	PRINTIFNPOSITIVE
	N @ N1 !
	0 N !
	A1 F@ Z F!
	TWO F@  W F@ FLN F*  A1 F@ FLN F/  FLOOR  F>D D>S  M !
	FALSE BREAK !
	BEGIN
		Z F@ X F!
		1 IVAR !
		SR3980
		Z F@ AINVRSE F@ F= IF
			TRUE BREAK !
		ELSE 
			AINVRSE F@ Z F!
		THEN
	BREAK @ INVERT WHILE
	REPEAT
	\ =============================================
		100 MILESTONE !
	\ =============================================
	\  POWERS OF RADIX HAVE BEEN TESTED,
	\         NEXT TRY A FEW PRIMES
	NOTRIALS @ M !
	THREE F@   Z F!
	BEGIN
		Z F@ X F!
		1 IVAR !
		SR3980
		BEGIN
			Z F@ TWO F@ F+ Z F!
		THREE F@  Z F@ THREE F@ F/ FLOOR F*  Z F@ F=  WHILE
		REPEAT
	Z F@  EIGHT F@ THREE F@ F* F<  WHILE
	REPEAT
	N @ 0> IF
		." ERRORS LIKE THIS MAY INVALIDATE FINANCIAL CALCULATIONS" CR
		." INVOLVING INTEREST RATES." CR
	THEN
	PRINTIFNPOSITIVE
	N1 @ N +!
	N @ 0=  IF ." ... NO DISCREPANCIES FOUND." CR THEN
	N @ 0> IF PAUSE ELSE CR THEN
	
;
\ END PART5


: PART6 ( -- )

	\ =============================================
	110 MILESTONE !
	\ =============================================
	." SEEKING UNDERFLOW THRESHOLDS UFTHOLD AND E0." CR
	U1 F@ D F!
	PRECISIONF F@  PRECISIONF F@ FLOOR  F<> IF
		BINVRSE F@ D F!
		PRECISIONF F@ X F!
		BEGIN
			D F@  BINVRSE F@ F*  D F!
			X F@  ONE F@ F-  X F!
		X F@ ZERO F@ F> WHILE
		REPEAT
	THEN
	ONE F@ Y F!
	D F@ Z F!
	\ ... D IS POWER OF 1/RADIX < 1.
	BEGIN
		Y F@ C F!
		Z F@ Y F!
		Y F@ Y F@ F* Z F!
	Y F@ Z F@ F>  Z F@ Z F@ F+ Z F@ F>  AND WHILE
	REPEAT
	C F@ Y F!
	Y F@ D F@ F* Z F!
	BEGIN
		Y F@ C F!
		Z F@ Y F!
		Y F@ D F@ F* Z F!
	Y F@  Z F@ F>  Z F@ Z F@ F+  Z F@ F>  AND WHILE
	REPEAT
	RADIX F@ TWO F@ F< IF  TWO  ELSE  RADIX THEN  F@ HINVRSE F!
	ONE F@ HINVRSE F@ F/ H F!
	\ ... 1/HINVRSE == H == MIN(1/RADIX, 1/2)
	ONE F@ C F@ F/ CINVRSE F!
	C F@ E0 F!
	E0 F@ H F@ F* Z F!
	\ ...1/RADIX^(BIG INTEGER) << 1 << CINVRSE == 1/C
	BEGIN
		E0 F@ Y F!
		Z F@ E0 F!
		E0 F@ H F@ F* Z F!
	E0 F@ Z F@ F>  Z F@ Z F@ F+ Z F@ F>  AND WHILE
	REPEAT
	E0 F@ UFTHOLD F!
	ZERO F@ E1 F!
	ZERO F@  Q F!
	U2 F@ E9 F!
	ONE F@ E9 F@ F+ S F!
	C F@ S F@ F* D F!
	D F@ C F@ F<=  IF
		RADIX F@ U2 F@ F* E9 F!
		ONE F@ E9 F@ F+ S F!
		C F@ S F@ F* D F!
		D F@ C F@ F<=  IF
			FAILURE S" MULTIPLICATION GETS TOO MANY LAST DIGITS WRONG." BADCOND
			E0 F@ UNDERFLOW F!
			ZERO F@ Y1 F!
			Z F@ PSEUDOZERO F!
			PAUSE
		THEN
	ELSE
		D F@ UNDERFLOW F!
		UNDERFLOW F@ H F@ F* PSEUDOZERO F!
		ZERO F@ UFTHOLD F!
		BEGIN
			UNDERFLOW F@ Y1 F!
			PSEUDOZERO F@ UNDERFLOW F!
			E1 F@ E1 F@ F+  E1 F@ F<=  IF
				UNDERFLOW F@ HINVRSE F@ F* Y2 F!
				Y1 F@  Y2 F@ F-  FABS E1 F!
				Y1 F@ Q F!
				UFTHOLD F@ ZERO F@ F=  Y1 F@ Y2 F@ F<>  AND IF Y1 F@ UFTHOLD F! THEN
			THEN
			PSEUDOZERO F@ H F@ F* PSEUDOZERO F!
		UNDERFLOW F@ PSEUDOZERO F@ F>
		PSEUDOZERO F@ PSEUDOZERO F@ F+  PSEUDOZERO F@ F> AND WHILE
		REPEAT
	THEN
	\ COMMENT LINE 4530 .. 4560
	PSEUDOZERO F@ ZERO F@ F<> IF
		CR
		PSEUDOZERO F@ Z F!
	\ ... TEST PSEUDOZERO FOR "PHONEY- ZERO" VIOLATES
	( ... PSEUDOZERO < UNDERFLOW OR PSEUDOZERO < PSEUDOZERO + PSEUDOZERO
		   ... )
		PSEUDOZERO F@ ZERO F@ F<=  IF
			FAILURE S" POSITIVE EXPRESSIONS CAN UNDERFLOW TO AN" BADCOND
			CR ." ALLEGEDLY NEGATIVE VALUE" CR
			." PSEUDOZERO THAT PRINTS OUT AS: " PSEUDOZERO F@ F. ( %G) CR
			PSEUDOZERO F@ FNEGATE X F!
			X F@ ZERO F@ F<=  IF
				." BUT -PSEUDOZERO, WHICH SHOULD BE" CR
				." POSITIVE, ISN'T; IT PRINTS OUT AS " X F@ F. ( %G) CR
			THEN
		ELSE
			FLAW S" UNDERFLOW CAN STICK AT AN ALLEGEDLY POSITIVE" BADCOND
			CR ." VALUE PSEUDOZERO THAT PRINTS OUT AS " PSEUDOZERO F@ F. ( %G) CR
		THEN
		TSTPTUF
	THEN
	\ =============================================
	120 MILESTONE !
	\ =============================================
	CINVRSE F@ Y F@ F*  CINVRSE F@ Y1 F@ F* F> IF
		H F@ S F@ F* S F!
		UNDERFLOW F@ E0 F!
	THEN
	E1 F@ ZERO F@ F=  E1 F@ E0 F@ F=  OR  INVERT IF
		DEFECT  S" " BADCOND
		E1 F@ E0 F@ F< IF
			." PRODUCTS UNDERFLOW AT A HIGHER"
			." THRESHOLD THAN DIFFERENCES." CR
			PSEUDOZERO F@ ZERO F@ F=  IF  E1 F@ E0 F!  THEN
		
		ELSE
			." DIFFERENCE UNDERFLOWS AT A HIGHER"
			." THRESHOLD THAN PRODUCTS." CR
		THEN
	THEN
	." SMALLEST STRICTLY POSITIVE NUMBER FOUND IS E0 = " E0 F@ FS. ( %G) CR
	E0 F@ Z F!
	TSTPTUF
	E0 F@ UNDERFLOW F!
	N @ 1 = IF  Y F@  UNDERFLOW F! THEN
	4 IVAR !
	E1 F@ ZERO F@ F=  IF  3 IVAR ! THEN
	UFTHOLD F@ ZERO F@ F=  IF  IVAR @ 2 - IVAR !  THEN
	TRUE UFNGRAD !
	IVAR @ CASE
		1 OF
		UNDERFLOW F@  UFTHOLD F!
		CINVRSE F@ Q F@ F*  CINVRSE F@ Y F@ F* S F@ F*  F<> IF
			Y F@ UFTHOLD F!
			FAILURE S" EITHER ACCURACY DETERIORATES AS NUMBERS" BADCOND
			CR ." APPROACH A THRESHOLD = " UFTHOLD F@ FS. ( %.17E)
			CR ." COMING DOWN FROM " C F@ FS. ( %.17E)
			CR ." OR ELSE MULTIPLICATION GETS TOO MANY LAST DIGITS WRONG." CR
		THEN
		PAUSE
		ENDOF

		2 OF
		FAILURE S" UNDERFLOW CONFUSES COMPARISON, WHICH ALLEGES THAT" BADCOND
		CR ." Q == Y WHILE DENYING THAT |Q - Y| == 0; THESE VALUES"
		CR ." PRINT OUT AS Q = " Q F@ FS. ( %.17E) ." , Y = " Y2 F@ FS. ( %.17E)
		CR ." |Q - Y| = " Q F@ Y2 F@ F- FABS FS. ( %.17E) CR
		Q F@ UFTHOLD F!
		ENDOF

		3 OF
		\ X = X    \ ??
		X F@ X F!
		ENDOF

		4 OF
		Q F@ UFTHOLD F@ F=  E1 F@ E0 F@ F=  AND
		UFTHOLD F@  E1 F@ E9 F@ F/ F- FABS   E1 F@ F<=  AND IF
			FALSE UFNGRAD !
			." UNDERFLOW IS GRADUAL; IT INCURS ABSOLUTE ERROR =" CR
			." (ROUNDOFF IN UFTHOLD) < E0." CR
			E0 F@ CINVRSE F@ F* Y F!
			Y F@  ONEANDHALF F@ U2 F@ F+ F*  Y F!
			CINVRSE F@  ONE F@ U2 F@ F+ F*  X F!
			Y F@ X F@ F/  Y F!
			Y F@ E0 F@ F=  IEEE !
		THEN
		ENDOF
	ENDCASE
	UFNGRAD @ IF
		CR
		\ SIGFPE SIGSAVE !
		\ SETJMP(OVFL_BUF)
		0 IF
			." UNDERFLOW / UFTHOLD FAILED!" CR
			R = H F@ H F@ F+  R F!
		ELSE 
			UNDERFLOW F@ UFTHOLD F@ F/ FSQRT  R F!
		THEN
		0 SIGSAVE !
		R F@ H F@ F<=  IF
			R F@ UFTHOLD F@ F*  Z F!
			Z F@  ONE F@  R F@ H F@ F*  ONE F@ H F@ F+ F* F+  F*  X F!
		ELSE
			UFTHOLD F@ Z F!
			Z F@  ONE F@  H F@ H F@ F*  ONE F@ H F@ F+ F* F+ F*  X F!
		THEN
		X F@ Z F@ F=   X F@ Z F@ F- ZERO F@ F<>  OR INVERT IF
			FLAW  S" "  BADCOND
			." X = " X F@ FS. ( %.17E) CR
			."     IS NOT EQUAL TO Z = " Z F@ FS. ( %.17E) CR
			X F@ Z F@ F- Z9 F!
			." YET X - Z YIELDS " Z9 F@ FS. ( %.17E) CR
			."    SHOULD THIS NOT SIGNAL UNDERFLOW, THIS IS A SERIOUS DEFECT"
			."    THAT CAUSES CONFUSION WHEN INNOCENT STATEMENTS LIKE" CR
			."    IF (X == Z)  ...  ELSE ... (F(X) - F(Z)) / (X - Z) ..." CR
			." ENCOUNTER DIVISION BY ZERO ALTHOUGH ACTUALLY" CR
			\ SIGFPE SIGSAVE !
			\ SETJMP(OVFL_BUF)
			0 IF
				." X / Z FAILS!" CR
			ELSE 
				." X / Z = 1 + " 
				X F@ Z F@ F/ HALF F@ F- HALF F@ F- F. ( %G) CR
			THEN
			0 SIGSAVE !
		THEN
	THEN
	." THE UNDERFLOW THRESHOLD IS "  UFTHOLD F@ FS. ( %.17E)
	." BELOW WHICH" CR
	." CALCULATION MAY SUFFER LARGER RELATIVE ERROR THAN MERELY ROUNDOFF." CR
	U1 F@ U1 F@ F*  Y2 F!
	Y2 F@ Y2 F@ F*  Y F!
	Y  F@ U1 F@ F*  Y2 F!
	Y2 F@  UFTHOLD F@ F<=  IF
		Y F@ E0 F@ F> IF
			DEFECT S" " BADCOND
			5 IVAR !
		ELSE
			SERIOUS  S" " BADCOND
			4 IVAR !
		THEN
		." RANGE IS TOO NARROW; U1^" IVAR ? ."  UNDERFLOWS." CR
	THEN
	\ =============================================
;
\ END PART6


: PART7_LOOPA ( -- )
	\ FOR(I = 1;;) {
	1 IVAR !
	BEGIN
		X F@  BINVRSE F@ F-  Z F!
		\ Z = (X + ONE) / (Z - (ONE - BINVRSE))
		X F@ ONE F@ F+  Z F@  ONE F@ BINVRSE F@ F- F-  F/  Z F!
		X F@ Z F@ POW  EXP2 F@ F- Q F!

		Q F@ FABS  TWOFORTY F@ U2 F@ F*  F> IF
			1 N !
	 		X F@ BINVRSE F@ F-  ONE F@ BINVRSE F@ F-  F-  V9 F!
			DEFECT S" CALCULATED " BADCOND
			X F@ Z F@ POW FS. ( %.17E) ." FOR" CR
			." (1 + (" V9 F@ FS. ( %.17E) ." ) ^ (" Z F@ FS. ( %.17E) ." );" CR
			." DIFFERS FROM CORRECT VALUE BY " Q F@ FS. ( %.17E) CR
			." THIS MUCH ERROR MAY SPOIL FINANCIAL" CR
			." CALCULATIONS INVOLVING TINY INTEREST RATES." CR
			EXIT \ BREAK;
		ELSE
			Y F@ X F@ F-  TWO F@ F*  Y F@ F+  Z F!
			Y F@ X F!
			Z F@ Y F!
			ONE F@  X F@ F9 F@ F-  X F@ F9 F@ F- F*  F+  Z F!
			Z F@ ONE F@ F>   IVAR @ NOTRIALS @ <  AND IF
				1 IVAR +!
			ELSE
				X F@ ONE F@ F> IF
					N @ 0=  IF
					   ." ACCURACY SEEMS ADEQUATE." CR
					THEN
					EXIT  \ BREAK;
				ELSE
					ONE F@ U2 F@ F+  X F!
					U2  F@ U2 F@ F+  Y F!
					Y   F@ X  F@ F+  Y F!
					1 IVAR !
				THEN
			THEN
		THEN
	AGAIN
;


: PART7 ( -- )

	\ =============================================
	130 MILESTONE !
	\ =============================================
	\ Y = - FLOOR(HALF - TWOFORTY * LOG(UFTHOLD) / LOG(HINVRSE)) / TWOFORTY;
	HALF F@ TWOFORTY F@ UFTHOLD F@ FLN F* HINVRSE F@ FLN F/ F- FLOOR
	TWOFORTY F@ F/ FNEGATE Y F!
	Y F@ Y F@ F+ Y2 F!
	." SINCE UNDERFLOW OCCURS BELOW THE THRESHOLD" CR
	." UFTHOLD = " HINVRSE F@ FS. ( %.17E) ." ^"  Y F@ FS. ( %.17E) CR
	." ONLY UNDERFLOW SHOULD AFFLICT THE EXPRESSION" CR
	."      "  HINVRSE F@ FS. ( %.17E) ." ^" Y2 F@ FS. ( %.17E) CR
	HINVRSE F@  Y2 F@  POW  V9 F!
	." ACTUALLY CALCULATING YIELDS: " V9 F@ FS. ( %.17E) CR
	V9 F@ ZERO F@ F>=
	V9 F@  RADIX F@ RADIX F@ F+ E9 F@ F+ UFTHOLD F@ F* F<=  AND  INVERT IF
		SERIOUS S" THIS IS NOT BETWEEN 0 AND UNDERFLOW" BADCOND
		."   THRESHOLD = " UFTHOLD F@ FS. ( %.17E) CR
	ELSE
		V9 F@   UFTHOLD F@  ONE F@ E9 F@ F+ F*  F>  INVERT IF
			." THIS COMPUTED VALUE IS O.K." CR
		ELSE
			DEFECT S" THIS IS NOT BETWEEN 0 AND UNDERFLOW" BADCOND
			."   THRESHOLD = "  UFTHOLD F@ FS. ( %.17E) CR
		THEN
	THEN
	\ =============================================
	140 MILESTONE !
	\ =============================================
	CR
	\ ...CALCULATE EXP2 == EXP(2) == 7.389056099...
	ZERO F@ X F!
	2 IVAR !
	TWO F@ THREE F@ F*  Y F!
	ZERO F@ Q F!
	0 N !
	BEGIN
		X F@ Z F!
		1 IVAR +!
		Y F@  IVAR @ IVAR @ + S>F F/  Y F!
		Y F@ Q F@ F+ R F!
		Z F@ R F@ F+ X F!
		Z F@ X F@ F- R F@ F+  Q F!
	X F@ Z F@ F>  WHILE
	REPEAT
	\ Z = (ONEANDHALF + ONE / EIGHT) + X / (ONEANDHALF * THIRTYTWO);
	ONEANDHALF F@  ONE F@ EIGHT F@ F/ F+
	X F@  ONEANDHALF F@ THIRTYTWO F@ F* F/ F+  Z F!
	Z F@ Z F@ F*  X F!
	X F@ X F@ F*  EXP2 F!
	F9 F@ X F!
	X F@ U1 F@ F-  Y F!
	." TESTING X^((X + 1) / (X - 1)) VS. EXP(2) = " EXP2 F@ FS. ( %.17E)
	." AS X -> 1." CR

	PART7_LOOPA

	\ =============================================
	150 MILESTONE !
	\ =============================================
	." TESTING POWERS Z^Q AT FOUR NEARLY EXTREME VALUES." CR
	0 N !
	A1 F@  Z F!
	HALF F@  C F@ FLN  A1 F@ FLN F/  F- FLOOR  Q F!
	FALSE BREAK !
	BEGIN
		CINVRSE F@ X F!
		Z F@ Q F@  POW  Y F!
		ISYEQX
		Q F@ FNEGATE Q F!
		C F@ X F!
		Z F@ Q F@  POW  Y F!
		ISYEQX
		Z F@  ONE F@ F<  IF
			TRUE BREAK !
		ELSE 
			AINVRSE F@ Z F!
		THEN
	BREAK @ INVERT  WHILE
	REPEAT 
	PRINTIFNPOSITIVE
	N @ 0=  IF  ." ... NO DISCREPANCIES FOUND." CR  THEN
	CR

	\ =============================================
	160 MILESTONE !
	\ =============================================
	PAUSE
	." SEARCHING FOR OVERFLOW THRESHOLD:" CR
	." THIS MAY GENERATE AN ERROR." CR
	CINVRSE F@ FNEGATE  Y F!
	HINVRSE F@  Y F@ F*  V9 F!
	\ SIGSAVE = SIGFPE;
	\ IF (SETJMP(OVFL_BUF)) { 0 IVAR !  Y F@ V9 F!  GOTO OVERFLOW; }
	BEGIN
		Y F@ V F!
		V9 F@ Y F!
		HINVRSE F@ Y F@ F* V9 F!
	V9 F@ Y F@ F< WHILE
	REPEAT
	1 IVAR !
\ OVERFLOW:
	0 SIGSAVE !
	V9 F@ Z F!
	." CAN `Z = -Y' OVERFLOW?" CR
	." TRYING IT ON Y = " Y F@ FS. ( %.17E) CR
	Y F@ FNEGATE V9 F!
	V9 F@ V0 F!
	V F@ Y F@ F-  V F@ V0 F@ F+  F=  IF
		." SEEMS O.K." CR
	ELSE
		." FINDS A "
		FLAW  S" -(-Y) DIFFERS FROM Y."  BADCOND
	THEN
	Z F@ Y F@  F<> IF
		SERIOUS  S" "  BADCOND
		." OVERFLOW PAST " Y F@ FS. ( %.17E) CR
		."    SHRINKS TO " Z F@ FS. ( %.17E) CR
	THEN
	IVAR @ IF
		V F@  HINVRSE F@ U2 F@ F*  HINVRSE F@ F- F*  Y F!
		Y F@  ONE F@ HINVRSE F@ F- U2 F@ F* V F@ F*  F+  Z F!
		Z F@ V0 F@  F<  IF  Z F@ Y F!  THEN
		Y F@ V0 F@  F<  IF  Y F@ V F!  THEN
		V0 F@ V F@ F-  V0 F@  F<  IF  V0 F@ V F! THEN
	ELSE
		Y F@  HINVRSE F@ * U2 F@ F* HINVRSE F@ F-  F*  V F!
		V F@  ONE F@  HINVRSE F@ F-  U2 F@ F*  Y F@ F*  F+  V F!
	THEN
	." OVERFLOW THRESHOLD IS V  = " V F@ FS. ( %.17E) CR
	IVAR @  IF
		 ." OVERFLOW SATURATES AT V0 = " V0 F@ FS. ( %.17E) CR
	ELSE 
		." THERE IS NO SATURATION VALUE BECAUSE THE SYSTEM TRAPS ON OVERFLOW." CR
	THEN
	V F@ ONE F@ F*  V9 F!
	." NO OVERFLOW SHOULD BE SIGNALED FOR V * 1 = " V9 F@ FS. ( %.17E) CR
	V F@ ONE F@ F/  V9 F!
	."                           NOR FOR V / 1 = " V9 F@ FS. ( %.17E) CR
	." ANY OVERFLOW SIGNAL SEPARATING THIS * FROM THE ONE" CR
	." ABOVE IS A DEFECT." CR
	\ =============================================
	170 MILESTONE !
	\ =============================================
	V F@ FNEGATE V F@ F<   V0 F@ FNEGATE V0 F@ F<  AND
	UFTHOLD F@ FNEGATE V F@ F<  AND  UFTHOLD F@ V F@ F<  AND  INVERT  IF
		FAILURE  S" COMPARISONS INVOLVING "  BADCOND
		." +-" V F@ F. ( %G) ." , +-" V0 F@ F. ( %G) ."  AND +-"
		UFTHOLD F@ F. ( %G) ."  ARE CONFUSED BY OVERFLOW."
	THEN
	\ =============================================
	175 MILESTONE !
	\ =============================================
	CR
	4 1 DO  \ FOR(INDX = 1; INDX <= 3; ++INDX) {
		I CASE
			1  OF  UFTHOLD    ENDOF
			2  OF  E0         ENDOF
			3  OF  PSEUDOZERO ENDOF
		ENDCASE
		F@  Z F!
		Z F@ ZERO F@ F<> IF
			Z F@ FSQRT V9 F!
			V9 F@ V9 F@ F*  Y F!
			Y F@  ONE F@ RADIX F@ E9 F@ F* F- F/  Z F@ F<
			Y F@  ONE F@  RADIX F@ E9 F@ F* F+ Z F@ F* F>  OR IF  \ DGH: + E9 --> * E9
				V9 F@ U1 F@ F> IF SERIOUS ELSE  DEFECT THEN S" " BADCOND

				." COMPARISON ALLEGES THAT WHAT PRINTS AS Z = "
				Z F@ FS. ( %.17E) CR
				." IS TOO FAR FROM SQRT(Z) ^ 2 = " Y F@ FS. ( %.17E) CR
			THEN
		THEN
	LOOP
	\ =============================================
	180 MILESTONE !
	\ =============================================
	3 1 DO  \ FOR(INDX = 1; INDX <= 2; ++INDX) {
		I 1 = IF  V ELSE  V0 THEN  F@ Z F!
		Z F@ FSQRT  V9 F!
		ONE F@ RADIX F@ E9 F@ F* F-  V9 F@ F*  X F!
		V9 F@ X F@ F*  V9 F!
		V9 F@  ONE F@  TWO F@ RADIX F@ F* E9 F@ F* F- Z F@ F*  F<
		V9 F@ Z F@ F>  OR   IF
			V9 F@  Y F!
			X F@  W F@ F<  IF  SERIOUS  ELSE  DEFECT  THEN
			S" "  BADCOND
			." COMPARISON ALLEGES THAT Z = "  Z F@ FS. ( %17E) CR
			." IS TOO FAR FROM SQRT(Z) ^ 2 (" Y F@ FS. ( %.17E) CR
		THEN
	LOOP
	\ =============================================
	
;
\ END PART7


: PART8 ( -- )
	\ =============================================
	190 MILESTONE !
	\ =============================================
	PAUSE
	UFTHOLD F@ V F@ F* X F!
	RADIX F@ RADIX F@  F* Y F!
	X F@ Y F@ F* ONE F@ F<   X F@ Y F@ F>  OR IF
		X F@ Y F@ F*  U1 F@ F<  X F@ > Y F@ U1 F@ F/ F>  OR IF
			DEFECT  S" BADLY"
		ELSE 
			FLAW S" "
		THEN
		BADCOND
		." UNBALANCED RANGE; UFTHOLD * V = " X F@ FS. ( %.17E) CR
		." IS TOO FAR FROM 1." CR
	THEN
	\ =============================================
	200 MILESTONE !
	\ =============================================
	6 1 DO  \ FOR (INDX = 1; INDX <= 5; ++INDX)  {
		F9 F@ X F!
		I CASE
			2 OF  ONE F@ U2 F@ F+  X F!  ENDOF
			3 OF  V F@  X F!             ENDOF
			4 OF  UFTHOLD F@       X F!  ENDOF
			5 OF  RADIX F@         X F!  ENDOF
		ENDCASE
		X F@ Y F!
		\ SIGSAVE = SIGFPE;
		\ IF (SETJMP(OVFL_BUF))
		\	PRINTF("  X / X  TRAPS WHEN X = %G\N", X);
		\ ELSE {
			Y F@ X F@ F/  HALF F@ F- HALF F@ F- V9 F!
			V9 F@ ZERO F@ F<> IF
				V9 F@ U1 F@ FNEGATE F=   I 5 <  AND
				IF  FLAW  ELSE SERIOUS  THEN  S" " BADCOND
				."  X / X DIFFERS FROM 1 WHEN X = " X F@ FS. ( %.17E) CR
				."  INSTEAD, X / X - 1/2 - 1/2 = " V9 F@ FS. ( %.17E) CR
			THEN
		\ }
		0 SIGSAVE !
	LOOP
	\ =============================================
	210 MILESTONE !
	\ =============================================
	ZERO F@ MYZERO F!
	CR
	." WHAT MESSAGE AND/OR VALUES DOES DIVISION BY ZERO PRODUCE?" CR

	NOPAUSE 0= IF
		." THIS CAN INTERUPT YOUR PROGRAM.  YOU CAN "
		." SKIP THIS PART IF YOU WISH." CR
		." DO YOU WISH TO COMPUTE 1 / 0? "
		KEY
		DUP [CHAR] Y = SWAP [CHAR] Y =  OR
	ELSE TRUE THEN

	IF
		\ SIGSAVE = SIGFPE;
		CR ."    TRYING TO COMPUTE 1 / 0 PRODUCES ..."
		\ IF (!SETJMP(OVFL_BUF)) PRINTF("  %.7E .\N", ONE / MYZERO);
		ONE F@ MYZERO F@ F/ FS. CR
		0 SIGSAVE !
	ELSE
		." O.K." CR
	THEN
	NOPAUSE 0= IF
		CR ." DO YOU WISH TO COMPUTE 0 / 0? "
		KEY
		DUP [CHAR] Y = SWAP [CHAR] Y =  OR
	ELSE TRUE THEN

	IF
		\ SIGSAVE = SIGFPE;
		CR ."    TRYING TO COMPUTE 0 / 0 PRODUCES ..."
		\ IF (!SETJMP(OVFL_BUF)) PRINTF("  %.7E .\N", ZERO / MYZERO);
		ZERO F@ MYZERO F@ F/ FS. CR
		0 SIGSAVE !
	ELSE 
		." O.K."  CR
	THEN

	\ =============================================
	220 MILESTONE !
	\ =============================================
	PAUSE
	CR
	." FAILURES  ENCOUNTERED = " ERRCNT{ FAILURE } ? CR
	." SERIOUS DEFECTS  DISCOVERED = " ERRCNT{ SERIOUS } ? CR
	." DEFECTS  DISCOVERED = " ERRCNT{ DEFECT } ? CR
	." FLAWS  DISCOVERED = " ERRCNT{ FLAW } ? CR

	CR
	ERRCNT{ FAILURE } @   ERRCNT{ SERIOUS } @ +
	ERRCNT{ DEFECT }  @ + ERRCNT{ FLAW } @  + 0> IF
		ERRCNT{ FAILURE } @  ERRCNT{ SERIOUS } @  +
		ERRCNT{ DEFECT } @ + 0=  ERRCNT{ FLAW } @ 0> AND IF
			." THE ARITHMETIC DIAGNOSED SEEMS "
			." SATISFACTORY THOUGH FLAWED." CR
		THEN
		ERRCNT{ FAILURE } @ ERRCNT{ SERIOUS } @ + 0=
		ERRCNT{ DEFECT } @ 0>  AND IF
			." THE ARITHMETIC DIAGNOSED MAY BE ACCEPTABLE" CR
			." DESPITE INCONVENIENT DEFECTS." CR
		THEN
		ERRCNT{ FAILURE } @ ERRCNT{ SERIOUS } @ +  0> IF
			." THE ARITHMETIC DIAGNOSED HAS "
			." UNACCEPTABLE SERIOUS DEFECTS." CR
		THEN
		ERRCNT{ FAILURE } @  0> IF
			." POTENTIALLY FATAL FAILURE MAY HAVE SPOILED THIS"
			." PROGRAM'S SUBSEQUENT DIAGNOSES." CR
		THEN
	ELSE
		." NO FAILURES, DEFECTS NOR FLAWS HAVE BEEN DISCOVERED." CR
		RMULT @ ROUNDED =   RDIV @ ROUNDED =  AND
		RADDSUB @ ROUNDED =  AND  RSQRT @ ROUNDED =  AND  INVERT IF
			." THE ARITHMETIC DIAGNOSED SEEMS SATISFACTORY." CR
		ELSE
			STICKYBIT F@ ONE F@ F>=
			RADIX F@ TWO F@ F-  RADIX F@ NINE F@ F- ONE F@ F- F* ZERO F@ F=
			AND  IF
			." ROUNDING APPEARS TO CONFORM TO THE PROPOSED IEEE STANDARD P"
			RADIX F@ TWO F@ F=
			PRECISIONF F@  FOUR F@ THREE F@ F* TWO F@ F* F-
			PRECISIONF F@ TWENTYSEVEN F@ F- TWENTYSEVEN F@ F- ONE F@ F+
			F*  ZERO F@ F=  AND  IF
					." 754"
				ELSE 
					." 854"
				THEN
				IEEE @ IF 
					CR
				ELSE
					CR ." EXCEPT FOR POSSIBLY DOUBLE ROUNDING"
					." DURING GRADUAL UNDERFLOW." CR
				THEN
			THEN
			." THE ARITHMETIC DIAGNOSED APPEARS TO BE EXCELLENT!" CR
		THEN
	THEN
	FPECOUNT @ IF
		CR ." A TOTAL OF " FPECOUNT ?
		."  FLOATING POINT EXCEPTIONS WERE REGISTERED." CR
	THEN
	." END OF TEST." CR
;
\ END PART8



: MAIN ( -- )
\ 0 [IF]
\ #IFDEF MC
\	CHAR *OUT;
\	IEEE_FLAGS("SET", "PRECISION", "DOUBLE", &OUT);
\ #ENDIF
\ [THEN]
	\ FIRST TWO ASSIGNMENTS USE INTEGER RIGHT-HAND SIDES.
	0 S>D D>F             ZERO  F!
	1 S>D D>F             ONE   F!
	ONE F@ ONE F@ F+      TWO   F!
	TWO F@ ONE F@ F+      THREE F!
	THREE F@ ONE F@ F+    FOUR  F!
	FOUR F@ ONE F@ F+     FIVE  F!
	FOUR F@ FOUR F@ F+    EIGHT F!
	THREE F@ THREE F@ F*  NINE  F!
	NINE F@ THREE F@ F*   TWENTYSEVEN F!
	FOUR F@ EIGHT F@ F*   THIRTYTWO F!
	FOUR F@ FIVE F@ F* THREE F@ F* FOUR F@ F* TWOFORTY F!
	ONE F@ FNEGATE        MINUSONE F!
	ONE F@ TWO F@ F/      HALF F!
	ONE F@ HALF F@ F+     ONEANDHALF F!

	0 ERRCNT{ FAILURE } !
	0 ERRCNT{ SERIOUS } !
	0 ERRCNT{ DEFECT } !
	0 ERRCNT{ FLAW } !

	1 PAGENO !
	\ =============================================
	0 MILESTONE !
	\ =============================================

	INSTRUCTIONS
	PAUSE
	HEADING
	PAUSE
	CHARACTERISTICS
	PAUSE
	HISTORY
	PAUSE
	
	\ =============================================
	7 MILESTONE !
	\ =============================================
	." PROGRAM IS NOW RUNNING TESTS ON SMALL INTEGERS:" CR

	FAILURE
	ZERO F@  ZERO F@ F+ ZERO F@  F=
	ONE  F@  ONE  F@ F- ZERO F@  F=  AND
	ONE  F@  ZERO F@             F>  AND
	ONE  F@  ONE  F@ F+ TWO F@   F=  AND
	S" 0+0 != 0, 1-1 != 0, 1 <= 0, OR 1+1 != 2"
	TSTCOND

	ZERO F@ FNEGATE  Z F!
	Z F@ 0E F<> IF
		1 ERRCNT{ FAILURE } +!
		." COMPARISON ALLEGES THAT -0.0 IS NON-ZERO!" CR
		0.001E U2 F!
		1E RADIX F!
		TSTPTUF
	THEN
 
	FAILURE
	TWO F@ ONE F@ F+ THREE F@  F=
	THREE F@ ONE F@ F+ FOUR F@ F=  AND
	FOUR F@ TWO F@ TWO F@ FNEGATE F* F+ ZERO F@ F=  AND
	FOUR F@ THREE F@ F- ONE F@ F- ZERO F@ F= AND
	S" 3 != 2+1, 4 != 3+1, 4+2*(-2) != 0, OR 4-3-1 != 0"
	TSTCOND

	FAILURE
	0E ONE F@ F- MINUSONE F@ F=
	MINUSONE F@ ONE F@ F+ ZERO F@ F=  AND
	ONE F@ MINUSONE F@ F+ ZERO F@ F=  AND
	MINUSONE F@ ONE F@ FABS F+ ZERO F@ F= AND
	MINUSONE F@ MINUSONE F@ MINUSONE F@ F* F+ ZERO F@ F= AND
	S" -1+1 != 0, (-1)+ABS(1) != 0, OR -1+(-1)*(-1) != 0"
	TSTCOND

	FAILURE
	HALF F@ MINUSONE F@ F+ HALF F@ F+ ZERO F@ F=
	S" 1/2 + (-1) + 1/2 != 0"
	TSTCOND

	\ =============================================

	PART2
	PART3
	PART4
	PART5
	PART6
	PART7
	PART8
;
\ END OF MAIN

\ CR CR .( TYPE "MAIN" TO START THE TESTS. )  CR

MAIN

CR .( END OF PARANOIA.FTH) CR
