define({COMPILE_CONSTANT_raw_body}, {
CELL .defer_call
FORTH$body$COMPILE_CONSTANT:
.globl FORTH$body$COMPILE_CONSTANT
.set "FORTH$body$COMPILE-CONSTANT", FORTH$body$COMPILE_CONSTANT
.globl "FORTH$body$COMPILE-CONSTANT"
CELL FORTH$SYS_COMPILE_CONSTANT
})
