define({COMPILE_EXECUTE_raw_body}, {
CELL .defer_call
FORTH$body$COMPILE_EXECUTE:
.globl FORTH$body$COMPILE_EXECUTE
.set "FORTH$body$COMPILE-EXECUTE", FORTH$body$COMPILE_EXECUTE
.globl "FORTH$body$COMPILE-EXECUTE"
CELL FORTH$SYS_COMPILE_EXECUTE
})
